In [1]:
# Imports
import polars as pl
from pathlib import Path
from IPython.display import display

## Load Data

In [2]:
# Read data from parquet file, otherwise read excel file and convert to parquet
# (With polars, parquet files are much faster to read from and write to)

path_excel = Path('./5 YR 2019-2023 STATEWIDE CRASH DATA.xlsx')
path_parquet_crashes = Path('./sheet_crashes.parquet')
path_parquet_persons = Path('./sheet_persons.parquet')
sheet_name_crashes = '2019-2023 STATEWIDE'
sheet_name_persons = 'PERSONS INVOLVED'

if path_parquet_crashes.exists() and path_parquet_persons.exists():
    print(f"Reading from parquet files: {path_parquet_crashes}, {path_parquet_persons}")
    sheet_crashes_original = pl.read_parquet(path_parquet_crashes)
    sheet_persons_original = pl.read_parquet(path_parquet_persons)
    print("Done reading parquet files")
else:
    print(f"No parquet file, reading from excel file: {path_excel}")
    sheet_crashes_original = pl.read_excel(path_excel, sheet_name=sheet_name_crashes, read_options={'schema_sample_rows': None})
    sheet_persons_original = pl.read_excel(path_excel, sheet_name=sheet_name_persons, read_options={'schema_sample_rows': None})
    print(f"Done reading excel file, writing to parquet files: {path_parquet_crashes}, {path_parquet_persons}")
    sheet_crashes_original.write_parquet(path_parquet_crashes)
    sheet_persons_original.write_parquet(path_parquet_persons)
    print(f"Written to parquet files")

Reading from parquet files: sheet_crashes.parquet, sheet_persons.parquet
Done reading parquet files

## Pre-process data

### Remove Completely Identical Crash Rows

In [3]:
# Find all rows that are completely identical
sheet_crashes_original.is_duplicated().value_counts()

shape: (2, 2)
┌───────┬────────┐
│       ┆ count  │
│ ---   ┆ ---    │
│ bool  ┆ u32    │
╞═══════╪════════╡
│ false ┆ 251784 │
│ true  ┆ 10     │
└───────┴────────┘

In [4]:
# Remove identical rows
sheet_crashes_no_identical = sheet_crashes_original.unique()
sheet_crashes_no_identical.is_duplicated().value_counts()

shape: (1, 2)
┌───────┬────────┐
│       ┆ count  │
│ ---   ┆ ---    │
│ bool  ┆ u32    │
╞═══════╪════════╡
│ false ┆ 251789 │
└───────┴────────┘

In [5]:
print(f"Removed: {sheet_crashes_original.shape[0] - sheet_crashes_no_identical.shape[0]}")

Removed: 5

### Remove rows with duplicate crash numbers

In [6]:
# Find all crashes with duplicate crash nums
sheet_crashes_dup = sheet_crashes_no_identical.filter(pl.col('CrashNum').is_duplicated()).sort(by='CrashNum')
sheet_crashes_dup.head()

shape: (5, 74)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CrashNum  ┆ Street1   ┆ Street1Ot ┆ Street1Lo ┆ … ┆ Measure   ┆ Secondary ┆ X         ┆ Y        │
│ ---       ┆ ---       ┆ her       ┆ cated     ┆   ┆ ---       ┆ Collision ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LVM230300 ┆ E         ┆ null      ┆ SR592     ┆ … ┆ 8.45881   ┆ NO        ┆ 671713.20 ┆ 3.9984e6 │
│ 114951    ┆ FLAMINGO  ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│           ┆ RD        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LVM230300 ┆ E         ┆ null      ┆ SR592     ┆ … ┆ 8.45881   ┆ null      ┆ 671713.20 ┆ 3.9984e6 │
│ 114951    ┆ FLAMINGO  ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│           ┆ RD        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ NHP221200 ┆ US95      ┆ null      ┆ US95S     ┆ … ┆ 40.719518 ┆ NO        ┆ 685483.85 ┆ 3.9615e6 │
│ 386       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 59        ┆          │
│ NHP221200 ┆ US95      ┆ null      ┆ US95S     ┆ … ┆ 40.719518 ┆ null      ┆ 685483.85 ┆ 3.9615e6 │
│ 386       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 59        ┆          │
│ NHP221200 ┆ SR160N    ┆ null      ┆ SR160N    ┆ … ┆ 10.927381 ┆ NO        ┆ 590286.87 ┆ 4.0092e6 │
│ 407       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 53        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Count ID counts
with pl.Config(tbl_rows=100):
    display(sheet_crashes_dup[:, 'CrashNum'].value_counts())

shape: (16, 2)
┌─────────────────┬───────┐
│ CrashNum        ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ LVM230300114951 ┆ 2     │
│ NHP221200386    ┆ 2     │
│ NHP221200407    ┆ 2     │
│ NHP230301584    ┆ 2     │
│ NYSO23NY-4072   ┆ 2     │
│ NYSO23NY-4263   ┆ 2     │
│ NYSO23NY-4264   ┆ 2     │
│ RPD23-21128     ┆ 2     │
│ RPD23-22397     ┆ 2     │
│ RPD23-23007     ┆ 2     │
│ SPPD23-2851     ┆ 2     │
│ SPPD23-7600     ┆ 2     │
│ SPPD23-8894     ┆ 2     │
│ SPPD23-9036     ┆ 2     │
│ SPPD23-9197     ┆ 2     │
│ SPPD23-9903     ┆ 2     │
└─────────────────┴───────┘

In [8]:
# Find differences between duplicate rows

def compare_pairs(df: pl.DataFrame, column_header: str, column_header2: str | None = None) -> None:
    """Print differences between each pairwise row."""
    for i in range(0, df.shape[0], 2):
        if column_header2 is not None:
            print(f"{df[i, column_header]!r}, {df[i, column_header2]!r}:")
        else:
            print(f"{df[i, column_header]!r}:")
        for column in df.columns:
            x = df[i, column]
            y = df[i+1, column]
            if x != y:
                print(f"[{i}, {column!r}]: {x!r}")
                print(f"[{i+1}, {column!r}]: {y!r}")

compare_pairs(sheet_crashes_dup, 'CrashNum')

'LVM230300114951':
[0, 'SecondaryCollision']: 'NO'
[1, 'SecondaryCollision']: None
'NHP221200386':
[2, 'CrashTime']: 905
[3, 'CrashTime']: 845
[2, 'ReportDate']: datetime.datetime(2023, 7, 5, 0, 0)
[3, 'ReportDate']: datetime.datetime(2022, 12, 14, 0, 0)
[2, 'NumOccupants']: 1
[3, 'NumOccupants']: 0
[2, 'SecondaryCollision']: 'NO'
[3, 'SecondaryCollision']: None
'NHP221200407':
[4, 'VehCrashType']: 'Unknown'
[5, 'VehCrashType']: 'SIDESWIPE - OVERTAKING'
[4, 'LocationFirstEvent']: 'Unknown'
[5, 'LocationFirstEvent']: 'TRAVEL LANE'
[4, 'LocationFirstEventTrav']: None
[5, 'LocationFirstEventTrav']: 2
[4, 'SecondaryCollision']: 'NO'
[5, 'SecondaryCollision']: None
'NHP230301584':
[6, 'DistLandmarkApprox']: 'NO'
[7, 'DistLandmarkApprox']: 'YES'
[6, 'ReportDate']: datetime.datetime(2023, 6, 20, 0, 0)
[7, 'ReportDate']: datetime.datetime(2023, 3, 21, 0, 0)
[6, 'SecondaryCollision']: 'NO'
[7, 'SecondaryCollision']: None
'NYSO23NY-4072':
[8, 'CrashDate']: datetime.datetime(2023, 11, 28, 0, 0)
[9, 'CrashDate']: datetime.datetime(2023, 11, 27, 16, 0)
[8, 'NotifiedDate']: datetime.datetime(2023, 11, 29, 0, 0)
[9, 'NotifiedDate']: datetime.datetime(2023, 11, 28, 16, 0)
[8, 'SecondaryCollision']: None
[9, 'SecondaryCollision']: 'NO'
'NYSO23NY-4263':
[10, 'CrashDate']: datetime.datetime(2023, 12, 14, 16, 0)
[11, 'CrashDate']: datetime.datetime(2023, 12, 15, 0, 0)
[10, 'NotifiedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[11, 'NotifiedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[10, 'ArrivedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[11, 'ArrivedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[10, 'ReportDate']: datetime.datetime(2023, 12, 14, 16, 0)
[11, 'ReportDate']: datetime.datetime(2023, 12, 15, 0, 0)
[10, 'SecondaryCollision']: 'NO'
[11, 'SecondaryCollision']: None
'NYSO23NY-4264':
[12, 'CrashDate']: datetime.datetime(2023, 12, 14, 16, 0)
[13, 'CrashDate']: datetime.datetime(2023, 12, 15, 0, 0)
[12, 'NotifiedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[13, 'NotifiedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[12, 'ArrivedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[13, 'ArrivedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[12, 'ReportDate']: datetime.datetime(2023, 12, 14, 16, 0)
[13, 'ReportDate']: datetime.datetime(2023, 12, 15, 0, 0)
[12, 'SecondaryCollision']: 'NO'
[13, 'SecondaryCollision']: None
'RPD23-21128':
[14, 'CrashDate']: datetime.datetime(2023, 11, 15, 16, 0)
[15, 'CrashDate']: datetime.datetime(2023, 11, 16, 0, 0)
[14, 'NotifiedDate']: datetime.datetime(2023, 11, 15, 16, 0)
[15, 'NotifiedDate']: datetime.datetime(2023, 11, 16, 0, 0)
[14, 'ArrivedDate']: datetime.datetime(2023, 11, 15, 16, 0)
[15, 'ArrivedDate']: datetime.datetime(2023, 11, 16, 0, 0)
[14, 'ReportDate']: datetime.datetime(2023, 11, 15, 16, 0)
[15, 'ReportDate']: datetime.datetime(2023, 11, 16, 0, 0)
[14, 'SecondaryCollision']: 'NO'
[15, 'SecondaryCollision']: None
'RPD23-22397':
[16, 'CrashDate']: datetime.datetime(2023, 12, 6, 0, 0)
[17, 'CrashDate']: datetime.datetime(2023, 12, 5, 16, 0)
[16, 'NotifiedDate']: datetime.datetime(2023, 12, 6, 0, 0)
[17, 'NotifiedDate']: datetime.datetime(2023, 12, 5, 16, 0)
[16, 'ArrivedDate']: datetime.datetime(2023, 12, 6, 0, 0)
[17, 'ArrivedDate']: datetime.datetime(2023, 12, 5, 16, 0)
[16, 'ReportDate']: datetime.datetime(2023, 12, 6, 0, 0)
[17, 'ReportDate']: datetime.datetime(2023, 12, 5, 16, 0)
[16, 'SecondaryCollision']: None
[17, 'SecondaryCollision']: 'NO'
'RPD23-23007':
[18, 'CrashDate']: datetime.datetime(2023, 12, 15, 0, 0)
[19, 'CrashDate']: datetime.datetime(2023, 12, 14, 16, 0)
[18, 'NotifiedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[19, 'NotifiedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[18, 'ArrivedDate']: datetime.datetime(2023, 12, 15, 0, 0)
[19, 'ArrivedDate']: datetime.datetime(2023, 12, 14, 16, 0)
[18, 'ReportDate']: datetime.datetime(2023, 12, 15, 0, 0)
[19, 'ReportDate']: datetime.datetime(2023, 12, 14, 16, 0)
[18, 'SecondaryCollision']: None
[19, 'SecondaryCollision']: 'NO'
'SPPD23-2851':
[20, 'SecondaryCollision']: None
[21, 'SecondaryCollision']: 'NO'
'SPPD23-7600':
[22, 'CrashDate']: datetime.datetime(2023, 10, 4, 0, 0)
[23, 'CrashDate']: datetime.datetime(2023, 10, 3, 17, 0)
[22, 'NotifiedDate']: datetime.datetime(2023, 10, 4, 0, 0)
[23, 'NotifiedDate']: datetime.datetime(2023, 10, 3, 17, 0)
[22, 'ArrivedDate']: datetime.datetime(2023, 10, 4, 0, 0)
[23, 'ArrivedDate']: datetime.datetime(2023, 10, 3, 17, 0)
[22, 'ReportDate']: datetime.datetime(2023, 10, 4, 0, 0)
[23, 'ReportDate']: datetime.datetime(2023, 10, 3, 17, 0)
[22, 'SecondaryCollision']: None
[23, 'SecondaryCollision']: 'NO'
'SPPD23-8894':
[24, 'CrashDate']: datetime.datetime(2023, 11, 18, 0, 0)
[25, 'CrashDate']: datetime.datetime(2023, 11, 17, 16, 0)
[24, 'NotifiedDate']: datetime.datetime(2023, 11, 18, 0, 0)
[25, 'NotifiedDate']: datetime.datetime(2023, 11, 17, 16, 0)
[24, 'ArrivedDate']: datetime.datetime(2023, 11, 18, 0, 0)
[25, 'ArrivedDate']: datetime.datetime(2023, 11, 17, 16, 0)
[24, 'ReportDate']: datetime.datetime(2023, 11, 18, 0, 0)
[25, 'ReportDate']: datetime.datetime(2023, 11, 17, 16, 0)
[24, 'SecondaryCollision']: None
[25, 'SecondaryCollision']: 'NO'
'SPPD23-9036':
[26, 'CrashDate']: datetime.datetime(2023, 11, 23, 0, 0)
[27, 'CrashDate']: datetime.datetime(2023, 11, 22, 16, 0)
[26, 'NotifiedDate']: datetime.datetime(2023, 11, 23, 0, 0)
[27, 'NotifiedDate']: datetime.datetime(2023, 11, 22, 16, 0)
[26, 'ArrivedDate']: datetime.datetime(2023, 11, 23, 0, 0)
[27, 'ArrivedDate']: datetime.datetime(2023, 11, 22, 16, 0)
[26, 'ReportDate']: datetime.datetime(2023, 11, 23, 0, 0)
[27, 'ReportDate']: datetime.datetime(2023, 11, 22, 16, 0)
[26, 'SecondaryCollision']: None
[27, 'SecondaryCollision']: 'NO'
'SPPD23-9197':
[28, 'CrashDate']: datetime.datetime(2023, 11, 29, 0, 0)
[29, 'CrashDate']: datetime.datetime(2023, 11, 28, 16, 0)
[28, 'NotifiedDate']: datetime.datetime(2023, 11, 29, 0, 0)
[29, 'NotifiedDate']: datetime.datetime(2023, 11, 28, 16, 0)
[28, 'ArrivedDate']: datetime.datetime(2023, 11, 29, 0, 0)
[29, 'ArrivedDate']: datetime.datetime(2023, 11, 28, 16, 0)
[28, 'ReportDate']: datetime.datetime(2023, 11, 29, 0, 0)
[29, 'ReportDate']: datetime.datetime(2023, 11, 28, 16, 0)
[28, 'SecondaryCollision']: None
[29, 'SecondaryCollision']: 'YES'
'SPPD23-9903':
[30, 'CrashDate']: datetime.datetime(2023, 12, 16, 0, 0)
[31, 'CrashDate']: datetime.datetime(2023, 12, 15, 16, 0)
[30, 'NotifiedDate']: datetime.datetime(2023, 12, 20, 0, 0)
[31, 'NotifiedDate']: datetime.datetime(2023, 12, 19, 16, 0)
[30, 'ArrivedDate']: datetime.datetime(2023, 12, 20, 0, 0)
[31, 'ArrivedDate']: datetime.datetime(2023, 12, 19, 16, 0)
[30, 'ReportDate']: datetime.datetime(2023, 12, 20, 0, 0)
[31, 'ReportDate']: datetime.datetime(2023, 12, 19, 16, 0)
[30, 'SecondaryCollision']: None
[31, 'SecondaryCollision']: 'NO'

In [9]:
# Assume that all rows with a non-null 'SecondaryCollision' value are more accurate.
# So, we will select all rows with null values and remove them
sheet_crashes_dup.filter(pl.col('SecondaryCollision').is_null())

shape: (16, 74)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CrashNum  ┆ Street1   ┆ Street1Ot ┆ Street1Lo ┆ … ┆ Measure   ┆ Secondary ┆ X         ┆ Y        │
│ ---       ┆ ---       ┆ her       ┆ cated     ┆   ┆ ---       ┆ Collision ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LVM230300 ┆ E         ┆ null      ┆ SR592     ┆ … ┆ 8.45881   ┆ null      ┆ 671713.20 ┆ 3.9984e6 │
│ 114951    ┆ FLAMINGO  ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│           ┆ RD        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ NHP221200 ┆ US95      ┆ null      ┆ US95S     ┆ … ┆ 40.719518 ┆ null      ┆ 685483.85 ┆ 3.9615e6 │
│ 386       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 59        ┆          │
│ NHP221200 ┆ SR160N    ┆ null      ┆ SR160N    ┆ … ┆ 10.927381 ┆ null      ┆ 590286.87 ┆ 4.0092e6 │
│ 407       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 53        ┆          │
│ NHP230301 ┆ US95S     ┆ null      ┆ US95S     ┆ … ┆ 89.701619 ┆ null      ┆ 650946.49 ┆ 4.0222e6 │
│ 584       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 91        ┆          │
│ NYSO23NY- ┆ POLE LINE ┆ null      ┆ POLE LINE ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 4072      ┆ RD ALT    ┆           ┆ RD ALT    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SPPD23-76 ┆ GREENBRAE ┆ null      ┆ GREENBRAE ┆ … ┆ 1.8437709 ┆ null      ┆ 264206.48 ┆ 4.3811e6 │
│ 00        ┆ DR        ┆           ┆ DR        ┆   ┆           ┆           ┆ 93        ┆          │
│ SPPD23-88 ┆ SPARKS    ┆ null      ┆ SPARKS    ┆ … ┆ 1.430986  ┆ null      ┆ 266667.87 ┆ 4.3804e6 │
│ 94        ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆ 55        ┆          │
│ SPPD23-90 ┆ E LINCOLN ┆ null      ┆ E LINCOLN ┆ … ┆ 0.273156  ┆ null      ┆ 264671.22 ┆ 4.3801e6 │
│ 36        ┆ WAY       ┆           ┆ WAY       ┆   ┆           ┆           ┆ 84        ┆          │
│ SPPD23-91 ┆ EL RANCHO ┆ null      ┆ EL RANCHO ┆ … ┆ 0.648852  ┆ null      ┆ 261450.58 ┆ 4.3809e6 │
│ 97        ┆ DR        ┆           ┆ DR        ┆   ┆           ┆           ┆ 53        ┆          │
│ SPPD23-99 ┆ LEXINGTON ┆ null      ┆ LEXINGTON ┆ … ┆ 0.00947   ┆ null      ┆ 263280.10 ┆ 4.3816e6 │
│ 03        ┆ WAY       ┆           ┆ WAY       ┆   ┆           ┆           ┆ 22        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
# Remove those rows
crash_nums_dup = set(sheet_crashes_dup[:, 'CrashNum'])
sheet_crashes_no_dup = sheet_crashes_no_identical.filter(pl.col('CrashNum').is_in(crash_nums_dup).not_() | pl.col('SecondaryCollision').is_not_null())
sheet_crashes_no_dup

shape: (251_773, 74)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CrashNum  ┆ Street1   ┆ Street1Ot ┆ Street1Lo ┆ … ┆ Measure   ┆ Secondary ┆ X         ┆ Y        │
│ ---       ┆ ---       ┆ her       ┆ cated     ┆   ┆ ---       ┆ Collision ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ NHP210601 ┆ IR15 N    ┆ null      ┆ IR15 N    ┆ … ┆ 19.095377 ┆ null      ┆ 657113.62 ┆ 3.9694e6 │
│ 588       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13        ┆          │
│ LVM230900 ┆ S EASTERN ┆ null      ┆ S EASTERN ┆ … ┆ 7.48879   ┆ NO        ┆ 669415.17 ┆ 3.9935e6 │
│ 037014    ┆ AVE       ┆           ┆ AVE       ┆   ┆           ┆           ┆ 68        ┆          │
│ LVM200300 ┆ W         ┆ null      ┆ W         ┆ … ┆ 4.5083386 ┆ null      ┆ 655700.98 ┆ 3.9981e6 │
│ 038767    ┆ FLAMINGO  ┆           ┆ FLAMINGO  ┆   ┆           ┆           ┆ 48        ┆          │
│           ┆ RD        ┆           ┆ RD        ┆   ┆           ┆           ┆           ┆          │
│ NLPD23060 ┆ N MARTIN  ┆ null      ┆ N MARTIN  ┆ … ┆ 4.192567  ┆ null      ┆ 665167.29 ┆ 4.0118e6 │
│ 60011432  ┆ L KING    ┆           ┆ L KING    ┆   ┆           ┆           ┆ 2         ┆          │
│           ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆           ┆          │
│ LVM191000 ┆ SWENSON   ┆ null      ┆ SWENSON   ┆ … ┆ 1.2746106 ┆ null      ┆ 666480.31 ┆ 3.9975e6 │
│ 067278    ┆ ST        ┆           ┆ ST        ┆   ┆           ┆           ┆ 4         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ NHP210401 ┆ OTHER     ┆ IR80      ┆ OTHER     ┆ … ┆ 0.4473911 ┆ null      ┆ 260380.09 ┆ 4.3799e6 │
│ 576       ┆           ┆ WESTBOUND ┆           ┆   ┆           ┆           ┆ 59        ┆          │
│           ┆           ┆ TRANSITIO ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ N RAMP    ┆           ┆   ┆           ┆           ┆           ┆          │
│ NHP210601 ┆ SR604     ┆ null      ┆ SR604     ┆ … ┆ 0.0894238 ┆ null      ┆ 667487.75 ┆ 4.0049e6 │
│ 328       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LVM230400 ┆ E         ┆ null      ┆ E         ┆ … ┆ 2.845061  ┆ null      ┆ 669276.26 ┆ 3.9871e6 │
│ 010929    ┆ SILVERADO ┆           ┆ SILVERADO ┆   ┆           ┆           ┆ 62        ┆          │
│           ┆ RANCH     ┆           ┆ RANCH     ┆   ┆           ┆           ┆           ┆          │
│           ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆           ┆          │
│ RPD23-183 ┆ E PLUMB   ┆ null      ┆ E PLUMB   ┆ … ┆ 0.754733  ┆ null      ┆ 260193.68 ┆ 4.3766e6 │
│ 0         ┆ LN        ┆           ┆ LN        ┆   ┆           ┆           ┆ 37        ┆          │
│ NHP231100 ┆ IR215S    ┆ CC215     ┆ IR215S    ┆ … ┆ 9.96623   ┆ NO        ┆ 665794.63 ┆ 3.9926e6 │
│ 598       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 76        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
sheet_crashes_no_dup[:, 'CrashNum'].is_duplicated().value_counts()

shape: (1, 2)
┌──────────┬────────┐
│ CrashNum ┆ count  │
│ ---      ┆ ---    │
│ bool     ┆ u32    │
╞══════════╪════════╡
│ false    ┆ 251773 │
└──────────┴────────┘

In [12]:
print("===Counts===")
print(f"                                Identical: {sheet_crashes_original.is_duplicated().value_counts().row(by_predicate=pl.col('') == True)[1]}")
print(f"        Duplicate CrashNum, not identical: {sheet_crashes_dup.shape[0]}")
print(f"                        Identical removed: {sheet_crashes_original.shape[0] - sheet_crashes_no_identical.shape[0]}")
print(f"Duplicate CrashNum, not identical Removed: {sheet_crashes_no_identical.shape[0] - sheet_crashes_no_dup.shape[0]}")
print(f"                            Total Removed: {sheet_crashes_original.shape[0] - sheet_crashes_no_dup.shape[0]}")

===Counts===
                                Identical: 10
        Duplicate CrashNum, not identical: 32
                        Identical removed: 5
Duplicate CrashNum, not identical Removed: 16
                            Total Removed: 21

### Remove Completely Identical Persons Rows

In [13]:
sheet_persons_original[:, ['CrashNum', 'pplNo']].is_duplicated().value_counts()

shape: (2, 2)
┌───────┬────────┐
│       ┆ count  │
│ ---   ┆ ---    │
│ bool  ┆ u32    │
╞═══════╪════════╡
│ true  ┆ 52     │
│ false ┆ 705429 │
└───────┴────────┘

In [14]:
sheet_persons_original.is_duplicated().value_counts()

shape: (2, 2)
┌───────┬────────┐
│       ┆ count  │
│ ---   ┆ ---    │
│ bool  ┆ u32    │
╞═══════╪════════╡
│ true  ┆ 42     │
│ false ┆ 705439 │
└───────┴────────┘

In [15]:
sheet_persons_no_identical = sheet_persons_original.unique()
print(f"{sheet_persons_original.shape = }")
print(f"{sheet_persons_no_identical.shape = }")
print(f"Removed: {sheet_persons_original.shape[0] - sheet_persons_no_identical.shape[0]}")
sheet_persons_no_identical.is_duplicated().value_counts()

sheet_persons_original.shape = (705481, 84)
sheet_persons_no_identical.shape = (705460, 84)
Removed: 21

shape: (1, 2)
┌───────┬────────┐
│       ┆ count  │
│ ---   ┆ ---    │
│ bool  ┆ u32    │
╞═══════╪════════╡
│ false ┆ 705460 │
└───────┴────────┘

### Remove persons rows with duplicate CrashNum, pplNo pairs

In [16]:
# Find all crashes with duplicate crash nums
sheet_persons_dup = sheet_persons_no_identical.filter(sheet_persons_no_identical[:, ['CrashNum', 'pplNo']].is_duplicated()).sort(by=('CrashNum', 'pplNo'))
sheet_persons_dup

shape: (10, 84)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ CrashNum  ┆ pplNo    ┆ vcNoRelat ┆ PersonTyp ┆ … ┆ VehicleSe ┆ NMVehActi ┆ NMVehActi ┆ NonMotorD │
│ ---       ┆ ---      ┆ ed        ┆ e         ┆   ┆ q1Harm    ┆ ons       ┆ onsOther  ┆ amageArea │
│ str       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ i64       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RPD23-223 ┆ 82071025 ┆ 79435511  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RPD23-223 ┆ 82071025 ┆ 79435511  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RPD23-223 ┆ 82071026 ┆ 79435512  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RPD23-223 ┆ 82071026 ┆ 79435512  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RPD23-230 ┆ 82285813 ┆ 0         ┆ Pedestria ┆ … ┆ null      ┆ Straight  ┆ null      ┆ null      │
│ 07        ┆          ┆           ┆ n         ┆   ┆           ┆           ┆           ┆           │
│ RPD23-230 ┆ 82285813 ┆ 0         ┆ Pedestria ┆ … ┆ null      ┆ Straight  ┆ null      ┆ null      │
│ 07        ┆          ┆           ┆ n         ┆   ┆           ┆           ┆           ┆           │
│ SPPD23-91 ┆ 81902340 ┆ 79280168  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPPD23-91 ┆ 81902340 ┆ 79280168  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPPD23-91 ┆ 81902341 ┆ 79280166  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPPD23-91 ┆ 81902341 ┆ 79280166  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 97        ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
compare_pairs(sheet_persons_dup, 'CrashNum', 'pplNo')

'RPD23-22397', 82071025:
[0, 'AlcDrugInvolved']: 'NONE'
[1, 'AlcDrugInvolved']: 'UNKNOWN'
[0, 'DrugSpecimen1']: 'FIELD SOBRIETY TEST'
[1, 'DrugSpecimen1']: None
[0, 'DrugSpecimen2']: 'BLOOD TEST'
[1, 'DrugSpecimen2']: None
[0, 'FieldSobrietyTest']: 'PASS'
[1, 'FieldSobrietyTest']: None
[0, 'UrineBloodRes']: 'NONE'
[1, 'UrineBloodRes']: None
'RPD23-22397', 82071026:
[2, 'PersonFactors']: 'UNKNOWN;'
[3, 'PersonFactors']: 'DRUG INVOLVEMENT;'
[2, 'AlcDrugInvolved']: 'UNKNOWN'
[3, 'AlcDrugInvolved']: 'DRUGS'
[2, 'DrugSpecimen1']: None
[3, 'DrugSpecimen1']: 'BLOOD TEST'
[2, 'UrineBloodRes']: None
[3, 'UrineBloodRes']: '1000 NG'
'RPD23-23007', 82285813:
[4, 'AlcDrugInvolved']: 'UNKNOWN'
[5, 'AlcDrugInvolved']: 'DRUGS'
[4, 'DrugSpecimen1']: None
[5, 'DrugSpecimen1']: 'BLOOD TEST'
[4, 'UrineBloodRes']: None
[5, 'UrineBloodRes']: 'FAIL'
[4, 'NMLocPrior2Imp']: 'UNKNOWN'
[5, 'NMLocPrior2Imp']: 'In Roadway'
[4, 'NMCondition']: 'UNKNOWN'
[5, 'NMCondition']: 'Under Influence: Med/Drugs/Alcohol'
[4, 'NMActions']: 'UNKNOWN'
[5, 'NMActions']: 'Other'
[4, 'NMActionsOther']: None
[5, 'NMActionsOther']: 'LYING IN ROADWAY'
[4, 'NMFactor']: '88|'
[5, 'NMFactor']: '3|'
'SPPD23-9197', 81902340:
[6, 'PersonFactors']: 'Apparently Normal'
[7, 'PersonFactors']: 'APPARENTLY NORMAL;'
'SPPD23-9197', 81902341:
[8, 'Sex']: 'M'
[9, 'Sex']: None
[8, 'DLClass']: 'C'
[9, 'DLClass']: None
[8, 'DLStatus']: 'Revoked'
[9, 'DLStatus']: None
[8, 'PersonFactors']: 'UNKNOWN;'
[9, 'PersonFactors']: None
[8, 'AlcDrugInvolved']: 'UNKNOWN'
[9, 'AlcDrugInvolved']: None

In [18]:
# Manually remove data (Removing data if it has more nulls)
sheet_persons_no_dup = sheet_persons_no_identical.clone()
sheet_persons_no_dup = sheet_persons_no_dup.remove(pl.col('CrashNum') == 'RPD23-22397', pl.col('pplNo') == 82071025, pl.col('DrugSpecimen1').is_null())
sheet_persons_no_dup = sheet_persons_no_dup.remove(pl.col('CrashNum') == 'RPD23-22397', pl.col('pplNo') == 82071026, pl.col('DrugSpecimen1').is_null())
sheet_persons_no_dup = sheet_persons_no_dup.remove(pl.col('CrashNum') == 'RPD23-23007', pl.col('pplNo') == 82285813, pl.col('DrugSpecimen1').is_null())
sheet_persons_no_dup = sheet_persons_no_dup.remove(pl.col('CrashNum') == 'SPPD23-9197', pl.col('pplNo') == 81902340, pl.col('PersonFactors') == 'Apparently Normal')  # Equal number of nulls
sheet_persons_no_dup = sheet_persons_no_dup.remove(pl.col('CrashNum') == 'SPPD23-9197', pl.col('pplNo') == 81902341, pl.col('Sex').is_null())
sheet_persons_no_dup

shape: (705_455, 84)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ CrashNum  ┆ pplNo    ┆ vcNoRelat ┆ PersonTyp ┆ … ┆ VehicleSe ┆ NMVehActi ┆ NMVehActi ┆ NonMotorD │
│ ---       ┆ ---      ┆ ed        ┆ e         ┆   ┆ q1Harm    ┆ ons       ┆ onsOther  ┆ amageArea │
│ str       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ i64       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ NLPD23050 ┆ 76799597 ┆ 74560714  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 20008770  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NLPD23090 ┆ 80316555 ┆ 0         ┆ Witness   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 90018101  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ LVM230900 ┆ 79856825 ┆ 0         ┆ Witness   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 006936    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NHP231100 ┆ 81520887 ┆ 78929115  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 682       ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ CCSO2021- ┆ 63464021 ┆ 62107080  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 4773      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ RPD23-657 ┆ 76475997 ┆ 74263211  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NHP211201 ┆ 66238198 ┆ 64731186  ┆ Passenger ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 904       ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NHP220801 ┆ 71710967 ┆ 69854546  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 602       ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NHP231200 ┆ 82206863 ┆ 79561117  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 749       ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ NHP191201 ┆ 34412188 ┆ 34172716  ┆ Driver    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 635       ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
print(f"{sheet_persons_no_identical.shape = }")
print(f"{sheet_persons_no_dup.shape = }")
print(f"Removed: {sheet_persons_no_identical.shape[0] - sheet_persons_no_dup.shape[0]}")

sheet_persons_no_identical.shape = (705460, 84)
sheet_persons_no_dup.shape = (705455, 84)
Removed: 5

### Convert to Uppercase

In [20]:
sheet_crashes_no_dup = sheet_crashes_no_dup.with_columns(pl.col('County').str.to_uppercase())
with pl.Config(tbl_rows=100):
    display(sheet_crashes_no_dup[:, 'County'].value_counts())

shape: (19, 2)
┌─────────────┬────────┐
│ County      ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ CHURCHILL   ┆ 2049   │
│ WASHOE      ┆ 35841  │
│ CARSON CITY ┆ 4342   │
│ DOUGLAS     ┆ 2899   │
│ CLARK       ┆ 188258 │
│ EUREKA      ┆ 499    │
│ LANDER      ┆ 509    │
│ NV          ┆ 6      │
│ PERSHING    ┆ 549    │
│ LYON        ┆ 2885   │
│ null        ┆ 2330   │
│ MINERAL     ┆ 441    │
│ NYE         ┆ 2848   │
│ WHITE PINE  ┆ 863    │
│ STOREY      ┆ 755    │
│ LINCOLN     ┆ 794    │
│ HUMBOLDT    ┆ 1355   │
│ ELKO        ┆ 4277   │
│ ESMERALDA   ┆ 273    │
└─────────────┴────────┘

## Analysis

### Join tables

In [21]:
print(f"{sheet_crashes_no_dup.shape = }")

sheet_crashes_no_dup.shape = (251773, 74)

In [22]:
# Check null counts
print(f"{sheet_crashes_no_dup[:, 'CrashNum'].null_count() = }")
print(f"{sheet_persons_no_dup[:, 'CrashNum'].null_count() = }")
print(f"{sheet_persons_no_dup[:, 'pplNo'].null_count()    = }")

sheet_crashes_no_dup[:, 'CrashNum'].null_count() = 0
sheet_persons_no_dup[:, 'CrashNum'].null_count() = 0
sheet_persons_no_dup[:, 'pplNo'].null_count()    = 0

In [23]:
# Check that the set of crash numbers from the persons table is a subset of
# of the set of crash numbers from the crashes table
crash_nums_crashes = set(sheet_crashes_no_dup[:, 'CrashNum'])
crash_nums_persons = set(sheet_persons_no_dup[:, 'CrashNum'])

print(f"{len(crash_nums_crashes) = }")
print(f"{len(crash_nums_persons) = }")
print(f"{crash_nums_crashes.issubset(crash_nums_persons) = }")
print(f"{crash_nums_persons.issubset(crash_nums_crashes) = }")

len(crash_nums_crashes) = 251773
len(crash_nums_persons) = 251506
crash_nums_crashes.issubset(crash_nums_persons) = False
crash_nums_persons.issubset(crash_nums_crashes) = True

In [24]:
# Join tables
sheet_joined = sheet_crashes_no_dup.join(sheet_persons_no_dup, on='CrashNum', how='left')
print(f"Joined table shape: {sheet_joined.shape}")
print(f"Unpaired rows: {sheet_joined[:, 'pplNo'].null_count()}")

Joined table shape: (705722, 157)
Unpaired rows: 267

### Does every row with PedestrianInvolved always include persons marked with "WheelChair"?

In [25]:
sheet_crashes_no_dup[:, 'PedestrianInvolved'].value_counts()

shape: (3, 2)
┌────────────────────┬────────┐
│ PedestrianInvolved ┆ count  │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│ YES                ┆ 4810   │
│ null               ┆ 136    │
│ NO                 ┆ 246827 │
└────────────────────┴────────┘

In [26]:
with pl.Config(tbl_rows=100):
    display(sheet_persons_no_dup[:, 'PersonType'].value_counts().sort('count', descending=True))

shape: (20, 2)
┌─────────────────────────────────┬────────┐
│ PersonType                      ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Driver                          ┆ 478985 │
│ Passenger                       ┆ 173408 │
│ Witness                         ┆ 44202  │
│ Pedestrian                      ┆ 5127   │
│ Pedal Cyclist                   ┆ 2331   │
│ Unknown                         ┆ 223    │
│ Other Non-Motorist              ┆ 202    │
│ Other                           ┆ 187    │
│ Wheelchair                      ┆ 163    │
│ E-Scooter                       ┆ 132    │
│ EMS                             ┆ 110    │
│ Skater                          ┆ 99     │
│ E-Bike                          ┆ 99     │
│ Fire                            ┆ 76     │
│ Occupant of MV not in transpor… ┆ 46     │
│ Police                          ┆ 37     │
│ null                            ┆ 20     │
│ Other Cyclist                   ┆ 6      │
│ Transportation                  ┆ 1      │
│ Tow Operator                    ┆ 1      │
└─────────────────────────────────┴────────┘

In [27]:
# Find rows with pedestrian
sheet_joined.filter(pl.col('PedestrianInvolved') == 'NO', pl.col('PersonType') == 'Wheelchair')

shape: (159, 157)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CrashNum  ┆ Street1   ┆ Street1Ot ┆ Street1Lo ┆ … ┆ VehicleSe ┆ NMVehActi ┆ NMVehActi ┆ NonMotor │
│ ---       ┆ ---       ┆ her       ┆ cated     ┆   ┆ q1Harm    ┆ ons       ┆ onsOther  ┆ DamageAr │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ea       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LVM190700 ┆ S BRUCE   ┆ null      ┆ S BRUCE   ┆ … ┆ 1         ┆ null      ┆ null      ┆ null     │
│ 007066    ┆ ST        ┆           ┆ ST        ┆   ┆           ┆           ┆           ┆          │
│ BCPD19BC0 ┆ US93 S    ┆ null      ┆ US93 S    ┆ … ┆ 1         ┆ Straight  ┆ null      ┆ UNKNOWN| │
│ 757       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ NLPD19020 ┆ N LAS     ┆ null      ┆ N LAS     ┆ … ┆ 1         ┆ Straight  ┆ null      ┆ FRONT|   │
│ 90002905  ┆ VEGAS     ┆           ┆ VEGAS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆           ┆          │
│ LVM211100 ┆ S DECATUR ┆ null      ┆ S DECATUR ┆ … ┆ 1         ┆ null      ┆ null      ┆ null     │
│ 019485    ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆           ┆          │
│ LVM190700 ┆ N EASTERN ┆ null      ┆ N EASTERN ┆ … ┆ 1         ┆ null      ┆ null      ┆ RIGHT    │
│ 043336    ┆ AVE       ┆           ┆ AVE       ┆   ┆           ┆           ┆           ┆ SIDE|    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LVM201200 ┆ S         ┆ null      ┆ S         ┆ … ┆ 1         ┆ null      ┆ null      ┆ null     │
│ 089371    ┆ MARYLAND  ┆           ┆ MARYLAND  ┆   ┆           ┆           ┆           ┆          │
│           ┆ PKWY      ┆           ┆ PKWY      ┆   ┆           ┆           ┆           ┆          │
│ LVM210700 ┆ E NAPLES  ┆ null      ┆ E NAPLES  ┆ … ┆ 1         ┆ null      ┆ null      ┆ null     │
│ 118136    ┆ DR        ┆           ┆ DR        ┆   ┆           ┆           ┆           ┆          │
│ LVM221000 ┆ W         ┆ null      ┆ W         ┆ … ┆ 1         ┆ Straight  ┆ null      ┆ FRONT|   │
│ 092547    ┆ TROPICANA ┆           ┆ TROPICANA ┆   ┆           ┆           ┆           ┆          │
│           ┆ AVE       ┆           ┆ AVE       ┆   ┆           ┆           ┆           ┆          │
│ NLPD21072 ┆ E OWENS   ┆ null      ┆ E OWENS   ┆ … ┆ 1         ┆ Straight  ┆ null      ┆ OTHER|   │
│ 80012788  ┆ AVE       ┆           ┆ AVE       ┆   ┆           ┆           ┆           ┆          │
│ LVM230100 ┆ S LAS     ┆ null      ┆ S LAS     ┆ … ┆ 1         ┆ null      ┆ null      ┆ null     │
│ 104528    ┆ VEGAS     ┆           ┆ VEGAS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ BLVD      ┆           ┆ BLVD      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Answer: Non-empty table, so yes

## Extract Pedestrian Data

In [28]:
# Get counts to know how many rows we are expecting.
group_by = sheet_joined.group_by('CrashNum')
any_pedestrian = (pl.col('PersonType') == 'Pedestrian').any()
any_wheelchair = (pl.col('PersonType') == 'Wheelchair').any()
any_pedestrian_involved_null = pl.col('PedestrianInvolved').is_null().any()
any_pedestrian_involved_yes = (pl.col('PedestrianInvolved') == 'YES').any()
any_pedestrian_involved_no = (pl.col('PedestrianInvolved') == 'NO').any()

print("PedestrianInvolved=null:")
print(group_by.agg(any_pedestrian_involved_null & any_pedestrian.not_() & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_null & any_pedestrian        & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_null & any_pedestrian.not_() & any_wheelchair       )[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_null & any_pedestrian        & any_wheelchair       )[:, 1].sum())

print("PedestrianInvolved=YES:")
print(group_by.agg(any_pedestrian_involved_yes & any_pedestrian.not_() & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_yes & any_pedestrian        & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_yes & any_pedestrian.not_() & any_wheelchair       )[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_yes & any_pedestrian        & any_wheelchair       )[:, 1].sum())

print("PedestrianInvolved=NO:")
print(group_by.agg(any_pedestrian_involved_no & any_pedestrian.not_() & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_no & any_pedestrian        & any_wheelchair.not_())[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_no & any_pedestrian.not_() & any_wheelchair       )[:, 1].sum())
print(group_by.agg(any_pedestrian_involved_no & any_pedestrian        & any_wheelchair       )[:, 1].sum())

PedestrianInvolved=null:
136
0
0
0
PedestrianInvolved=YES:
4
4802
0
4
PedestrianInvolved=NO:
246665
4
158
0

In [29]:
# Get crash numbers
crash_nums_pedestrian = set(group_by.agg(any_pedestrian_involved_yes | any_pedestrian | any_wheelchair).filter(pl.col('PedestrianInvolved'))[:, 'CrashNum'])
crash_nums_pedestrian

{'LVM230300003533',
 'LVM211000049473',
 'NHP220501640',
 'LVM230900093024',
 'NHP210200806',
 'RPD19-599',
 'RPD20-17533',
 'RPD20-19432',
 'LVM201000054121',
 'LVM211100082240',
 'LVM230400069166',
 'LVM200500038930',
 'LVM210400103842',
 'LVM221100083376',
 'RPD20-15924',
 'LVM231200034553',
 'NLPD200706010941',
 'LVM210200024954',
 'LVM220800065947',
 'LVM220100028323',
 'ELPD2020-18238',
 'LVM201100102878',
 'LVM230100000591',
 'CLSD22052657',
 'LVM191100028103',
 'HP23-12126',
 'LVM210800081467',
 'LVM230200103630',
 'LVM230800083213',
 'NLPD2011140018903',
 'LVM211000083258',
 'LVM210900007883',
 'LVM210200090076',
 'LVM221100024868',
 'LVM190600137330',
 'SPPD22-9568',
 'NHP231200079',
 'RPD22-16797',
 'LVM210700030792',
 'LVM191100020280',
 'LVM190900132218',
 'WASO23-5138',
 'NLPD2308300017401',
 'LVM200200107091',
 'LVM221200016065',
 'WASD19W-00746',
 'LVM231200039816',
 'LVM191100142184',
 'NLPD2107280012788',
 'LVM220900016421',
 'LVM211200107609',
 'WASO22-5037',
 'LVM190100044433',
 'LVM200700059686',
 'LVM210800078107',
 'NLPD2310110020400',
 'LVM231200064416',
 'RPD23-17026',
 'HP22-21982',
 'LVM220600045825',
 'RPD23-16859',
 'LVM231200066601',
 'NLPD2301150000953',
 'RPD20-18633',
 'NHP230200969',
 'NLPD2308090015870',
 'LVM230400115100',
 'NHP220201463',
 'NYSO22NY-1373',
 'LVM200800079561',
 'LVM200300129141',
 'LVM210100032101',
 'LVM220600100990',
 'LVM230600074325',
 'LVM211000077329',
 'LVM191100058208',
 'RPD19-15222',
 'LVM210100085900',
 'RPD22-14927',
 'LVM200100129053',
 'LVM220500049066',
 'LVM210800096777',
 'LVM230300060964',
 'LVM230400076302',
 'LVM221000117310',
 'LVM220700110170',
 'LVM200200038016',
 'HP21-21996',
 'LVM191100007690',
 'LVM220100021059',
 'LVM211000061350',
 'HP22-09552',
 'LVM210600132369',
 'LVM201200114523',
 'LVM220600032136',
 'SPPD19-3393',
 'LVM211100109427',
 'NHP220101526',
 'LVM230800008193',
 'NHP210902208',
 'LVM220400068732',
 'LVM220300003109',
 'RPD22-13974',
 'LVM220800034223',
 'NHP230501429',
 'LVM220700087443',
 'NHP190302239',
 'LVM200100143808',
 'LVM230200091389',
 'NLPD2309140018475',
 'RPD22-106058',
 'CCSO23-7760',
 'LVM220300128155',
 'LVM200100032937',
 'NYSO23NY-2181',
 'LVM200400101781',
 'LVM221000077784',
 'LVM201100108818',
 'LVM230800089684',
 'HP22-04346',
 'LVM220700029266',
 'LVM220300121746',
 'NLPD1910070020340',
 'NLPD2110080017400',
 'LVM220500123989',
 'NHP210100833',
 'LVM210900091286',
 'SPPD20-673',
 'NHP210400433',
 'LVM200700112716',
 'LVM211100030116',
 'LVM190200028426',
 'LVM220500090960',
 'RPD23-9060',
 'RPD23-5461',
 'LVM200800095466',
 'NLPD1905110009805',
 'RPD23-4835',
 'NHP231201679',
 'NLPD2202050002200',
 'NLPD2107190012209',
 'LVM211100127269',
 'LVM231200081424',
 'LVM220900042245',
 'LVM200200010578',
 'RPD22-8435',
 'MSPD211114033',
 'LVM200600089324',
 'LVM220300068562',
 'NLPD2103280005182',
 'LVM230600071378',
 'CLSD23100711',
 'LVM210700048568',
 'RPD21-19899',
 'NLPD2004290007314',
 'LVM220400008425',
 'LVM210700091976',
 'LVM231000069356',
 'LVM200100006109',
 'HP19-04747',
 'LVM220900107197',
 'LVM210700091097',
 'NHP200301648',
 'LVM200600068600',
 'LVM190800109018',
 'LVM220600065591',
 'LVM220600053777',
 'LVM210500015467',
 'NLPD2002060002524',
 'LVM220800054164',
 'LVM210700123592',
 'LVM201000086658',
 'RPD22-15565',
 'LVM190400031922',
 'NHP190101029',
 'NHP230200051',
 'NLPD2311210023257',
 'LVM191100130187',
 'NHP190601439',
 'RPD21-2476',
 'LVM210400003800',
 'NHP190901680',
 'RPD21-4284',
 'HP21-22270',
 'LVM201000049042',
 'LVM190700131611',
 'NLPD1901080000563',
 'RPD23-9612',
 'LVM210100091100',
 'NHP200201668',
 'LVM230400020346',
 'LVM200200013032',
 'SPPD21-8661',
 'LVM190800052561',
 'LVM200300055454',
 'LVM230900020353',
 'RPD20-17935',
 'LVM211200094600',
 'UNRUN23-134',
 'ELPD2019-20733',
 'RPD19-10754',
 'LVM230100046143',
 'LVM220700068606',
 'LVM191000017330',
 'NHP231200194',
 'LVM231000081141',
 'SPPD21-5560',
 'LVM220700108380',
 'LVM191100022082',
 'HP23-10492',
 'LVM200200030844',
 'LVM211000007351',
 'LVM220600043651',
 'NLPD2302230003744',
 'RPD20-354',
 'RPD21-24557',
 'LVM231000069315',
 'LVM230600020021',
 'LVM211000020073',
 'LVM190800037586',
 'LVM191200116277',
 'NYSO21NY-3516',
 'NLPD2109200016174',
 'LVM230500032657',
 'LVM200400005211',
 'LVM230700108940',
 'LVM230200010034',
 'LVM190800075610',
 'LVM230600104299',
 'HP22-19242',
 'LVM220900076426',
 'LVM211000109634',
 'LVM191100056257',
 'LVM231100077722',
 'RPDRP19-3351',
 'NLPD2303290006199',
 'LVM221200089103',
 'LVM200200074600',
 'LVM210700001796',
 'RPD21-21101',
 'LVM190100066088',
 'LVM221100059952',
 'LVM190100045573',
 'LVM201000015306',
 'HP20-02264',
 'LVM210700061523',
 'CLSD22050648',
 'LVM190800097409',
 'LVM220800107528',
 'HP22-21515',
 'LVM230700041467',
 'LVM190700149424',
 'NHP220900737',
 'NLPD2311220023340',
 'LVM221100077680',
 'RPD21-2923',
 'NHP210101950',
 'LVM200900114156',
 'LVM230500114995',
 'LVM230600133589',
 'LVM221200053201',
 'NHP200801561',
 'LVM190700048565',
 'LVM230400111143',
 'LVM220900019737',
 'HP21-12015',
 'NHP231001739',
 'LVM221100025007',
 'RPD19-24971',
 'LVM200600028131',
 'LVM210900052501',
 'NHP211200769',
 'LVM221100007564',
 'LVM191200136412',
 'LVM220800108521',
 'LVM210300089789',
 'LVM200100022808',
 'LVM221200110406',
 'LVM191200000676',
 'LVM220700038039',
 'WNPD22-0058',
 'NHP211200415',
 'LVM220200031508',
 'LVM210200021383',
 'SPPD21-3656',
 'LVM210800126298',
 'LVM200300035462',
 'LVM210100099647',
 'NLPD2101210001329',
 'LVM190400113552',
 'RPD22-12448',
 'LVM231100007151',
 'LVM220400125411',
 'RPD21-8931',
 'LVM230200066903',
 'RPD19-8612',
 'LVM230100015790',
 'LVM220600113842',
 'NLPD1905240010739',
 'HP22-02951',
 'LVM190300092018',
 'RPD23-22268',
 'NLPD2112290022572',
 'NHP211000383',
 'LVM190100131926',
 'WASO23-5769',
 'LVM190600111964',
 'LVM210800025818',
 'RPD23-16117',
 'LVM210200099919',
 'HP20-05213',
 'LVM210900008457',
 'LVM220400118618',
 'LVM220200068833',
 'HP23-08282',
 'LVM190200045069',
 'CCSO21-8182',
 'LVM201100095620',
 'LVM220200065202',
 'LVM220700075891',
 'LVM230100080996',
 'NHP231101256',
 'NHP230300267',
 'HP23-21441',
 'LVM210100081710',
 'HP19-30132',
 'NLPD1902210003729',
 'LVM190100094629',
 'CCSO22-1568',
 'LVM210200078462',
 'LVM190500141009',
 'LVM201000010176',
 'NHP231201368',
 'HP23-21233',
 'CCSO19-5149',
 'LVM220200015738',
 'LVM200100059271',
 'LVM210500022427',
 'LVM210900002589',
 'NLPD2311300023793',
 'LVM191200070227',
 'NHP230400150',
 'LVM211200040905',
 'LVM221100050078',
 'HP22-12066',
 'LVM211100033985',
 'HP22-00215',
 'LVM210500038297',
 'RPD23-10802',
 'LVM200400032145',
 'LVM220600081385',
 'LVM211000068239',
 'LVM211000050906',
 'NHP230100634',
 'LVM200600062296',
 'LVM230800048549',
 'LVM221200051420',
 'LVM191100046293',
 'HP23-04775',
 'NYSO21NY-2371',
 'LVM230800070923',
 'LVM220800040074',
 'LVM200800043652',
 'LVM190400122854',
 'RPD19-13637',
 'LVM230800103681',
 'RPD21-22507',
 'RPD19-6363',
 'HP21-04429',
 'LVM211100093331',
 'LVM221200102522',
 'LVM210900125442',
 'HP21-24005',
 'LVM220900034323',
 'LVM191000097162',
 'LVM200100023106',
 'LVM201200069163',
 'SPPD21-5344',
 'RPD19-9143',
 'LVM220400083601',
 'LVM210200037594',
 'RPD23-16286',
 'LVM230100084576',
 'LVM190400139875',
 'LVM210200119548',
 'LVM210200046783',
 'LVM190200122716',
 'LVM210800108041',
 'LVM210500113679',
 'NLPD1910080020473',
 'NLPD2106300010976',
 'RPD21-17951',
 'SPPD21-5292',
 'LVM231100033684',
 'LVM221000065304',
 'LVM190200083926',
 'LVM190800058103',
 'LVM230500144214',
 'NHP201200774',
 'HP20-00424',
 'RPD22-102418',
 'RPD23-1373',
 'LVM230600116008',
 'LVM200400101545',
 'LVM190300119597',
 'LVM200700114228',
 'NLPD1910180021094',
 'RPD22-23800',
 'SPPD21-4979',
 'LVM230700087240',
 'LVM221000112844',
 'RPD19-5327',
 'LVM210500059500',
 'NLPD1911140022928',
 'NLPD2003010004260',
 'LVM210100130415',
 'NLPD2007220011870',
 'LVM221200115357',
 'NHP201100412',
 'LVM230200095710',
 'LVM220700118876',
 'LVM200300020875',
 'HP21-17634',
 'LVM210400044755',
 'LVM220500059620',
 'LVM201000043172',
 'LVM221200091638',
 'LVM191200061141',
 'LVM190800059268',
 'RPD19-15770',
 'LVM210200011965',
 'CLSD22086557',
 'LVM231200090801',
 'RPD19-8561',
 'NLPD1906010011295',
 'NLPD1902010002266',
 'LYSO21LY02913',
 'LVM220700020089',
 'LVM201200003132',
 'LVM210700010506',
 'NLPD2309180018683',
 'LVM191000075719',
 'LVM230300042433',
 'ELPD23EP17343',
 'SPPD23-4475',
 'RPD22-20053',
 'HP20-22721',
 'LVM190400148790',
 'LVM220400070233',
 'LVM211000120241',
 'NHP210702451',
 'LVM211000132990',
 'LVM230100106098',
 'HP20-22732',
 'SPPD20-7928',
 'LVM220900081394',
 'LVM190100123803',
 'LVM200900037689',
 'LVM221200033741',
 'CLSD22099700',
 'LVM220700075716',
 'LVM220400127991',
 'LVM230800107323',
 'LVM190900143308',
 'NLPD2112030021058',
 'CLSD19-019024',
 'LVM211100040907',
 'SPPD22-6787',
 'NHP190101646',
 'NLPD2211100021466',
 'RPD20-14623',
 'HP23-10071',
 'LVM200200119516',
 'LVM190900075665',
 'LVM190100145377',
 'LVM200900011629',
 'LVM191100055272',
 'SPPD23-7880',
 'SPPD21-2000',
 'NLPD190329006583',
 'SPPD22-5641',
 'RPD19-23499',
 'NHP190902171',
 'RPD19-22365',
 'NHP191101088',
 'LVM231000092555',
 'LVM231200048784',
 'LVM210400076949',
 'RPD19-24347',
 'LVM240100000737',
 'HP21-07198',
 'NHP210601238',
 'LVM190200002335',
 'NYSO20NY-1447',
 'CLSD22057113',
 'RPD21-5905',
 'HP22-11486',
 'LVM220700052945',
 'LVM191000119273',
 'LVM190900064385',
 'LVM230800102750',
 'LVM220100033426',
 'LVM190600137372',
 'SPPD23-9541',
 'LVM201200055416',
 'LVM200400112248',
 'LVM200700087809',
 'CCSO23-116',
 'LVM210600040660',
 'LVM230800078805',
 'LVM210900070050',
 'NHP200600389',
 'LVM230500091627',
 'NHP190801308',
 'HP22-10023',
 'LVM190300133132',
 'LVM210100131699',
 'LVM210800132449',
 'BCPD23BC0204',
 'LVM211200025685',
 'LVM200500137540',
 'LVM190100042579',
 'LVM201200092660',
 'HP23-06062',
 'LVM200300081822',
 'NLPD2205200009218',
 'LVM230100052229',
 'LVM230500112290',
 'LVM201200073414',
 'LVM230800082474',
 'LVM221000048107',
 'NHP190501604',
 'LVM220800034681',
 'LVM220400089069',
 'LVM190900119099',
 'LVM200700074159',
 'RPD19-19583',
 'LVM230700100746',
 'LVM211100099577',
 'LVM231100023321',
 'LVM190600114425',
 'LVM230100016525',
 'LVM190100112248',
 'LVM230300132378',
 'CLSD21141870',
 'LVM220200015558',
 'HP20-03338',
 'RPD22-5984',
 'NHP230500073',
 'NHP190300459',
 'LVM211000086126',
 'LVM230500126735',
 'LVM230800104184',
 'LVM231000067222',
 'LVM211100022688',
 'LVM190200091728',
 'RPD19-4174',
 'NHP200301591',
 'LVM210900053540',
 'LVM220500069668',
 'LVM210400072978',
 'LVM230600101871',
 'RPD19-10805',
 'ELPD2021-17097',
 'LVM211100083612',
 'LVM191100051202',
 'LVM220700061393',
 'LVM230300052631',
 'LVM210900089393',
 'LVM201100125018',
 'LVM201100066490',
 'LVM230700129472',
 'RPD23-5057',
 'LVM230300115188',
 'NHP230201067',
 'SPPD23-9340',
 'RPD22-21018',
 'NHP231201156',
 'LVM191200032108',
 'NLPD1909100018485',
 'LVM200500151523',
 'NHP200301172',
 'RPD19-20024',
 'NHP231200999',
 'LVM220800007646',
 'LVM220300030321',
 'NHP210501093',
 'RPD19-1904',
 'LVM190800125367',
 'LVM211100041076',
 'LVM220900073199',
 'NLPD1903180005622',
 'LVM231200048874',
 'LVM220600034817',
 'LVM210500087644',
 'HP22-12127',
 'NHP231200881',
 'NLPD2009090014857',
 'LVM200100037514',
 'NLPD2108010013033',
 'LVM221100062590',
 'HP22-23123',
 'RPD19-23218',
 'RPD21-2616',
 'LVM210600010053',
 'LVM210300135944',
 'RPD22-9856',
 'LVM231100049779',
 'RPD19-22147',
 'RPD22-6735',
 'RPD19-2131',
 'NHP230300146',
 'NLPD2011220019376',
 'NLPD2009010014423',
 'LVM201200060195',
 'LVM230600122073',
 'RPD21-10367',
 'LVM190900131089',
 'LVM211000026285',
 'LVM220200013566',
 'LVM221000010204',
 'RPD22-15430',
 'LVM210800021825',
 'LVM220300083590',
 'RPD19-24420',
 'LVM190100047907',
 'NHP200100971',
 'LVM210400017451',
 'LVM210400099125',
 'LVM190200100303',
 'LVM201100066313',
 'LVM220800097335',
 'LVM220100041322',
 'WNPD21-0949',
 'LVM230200057024',
 'WASO22-4905',
 'LVM200200066121',
 'LVM220800105246',
 'LVM230400118788',
 'HP23-14994',
 'LVM190100024614',
 'LVM231000029300',
 'CCSO19-2529',
 'LVM191100141778',
 'RPD22-8456',
 'LVM191100084580',
 'LVM210200005691',
 'LVM231000095685',
 'LVM231100021644',
 'NLPD22829',
 'LVM200500142070',
 'LVM190400029187',
 'LVM210100116515',
 'LVM231000089977',
 'LVM220800072453',
 'LVM191100023845',
 'LVM221000069403',
 'LVM211100057564',
 'LVM210900061082',
 'LVM220300045765',
 'ELPD2022-08903',
 'LVM230500103410',
 'RPD19-324',
 'LVM190600034103',
 'LVM211200078780',
 'NHP190800200',
 'LVM190300124175',
 'LVM230200065367',
 'LVM231100040111',
 'NHP230701535',
 'LVM231100091591',
 'RPD22-18822',
 'LVM220500058991',
 'NLPD2210180019844',
 'LVM191200016706',
 'LVM220400028106',
 'LVM221000002730',
 'BCPD23BC0409',
 'LVM221100113785',
 'HP19-23660',
 'LVM190600077545',
 'LVM220800024420',
 'LVM230400067550',
 'RPD20-2881',
 'RPD20-1053',
 'LVM190700043257',
 'RPD19-19372',
 'RPD20-22894',
 'LVM190100127367',
 'RPD22-15968',
 'LVM190300072606',
 'LVM220400122313',
 'HP22-04056',
 'LVM231000104841',
 'NHP210801180',
 'LVM230900070849',
 'FAPDTA21-0073',
 'NLPD2305130009573',
 'LVM230600088437',
 'LVM231200098153',
 'LVM191100009667',
 'LVM190800123796',
 'NHP220901258',
 'LVM210400025745',
 'LYSO22LY05261',
 'LVM210500131093',
 'LVM221000000961',
 'LVM190200061510',
 'LVM190500079561',
 'LVM220200057983',
 'NLPD2111130019745',
 'NLPD2104300007209',
 'LVM191200097791',
 'LVM201000106994',
 'LVM200400071199',
 'NLPD1911230023508',
 'LVM200300144477',
 'NLPD2003100004806',
 'LVM200100100596',
 'LVM200700010473',
 'LVM190700119832',
 'RPD22-20840',
 'LVM221100111257',
 'LVM191000097272',
 'LVM191100131994',
 'LVM230900019012',
 'HP22-09662',
 'RPD19-22576',
 'HP19-10255',
 'HP20-18464',
 'LVM220300015277',
 'LVM211000015724',
 'NLPD2311040022131',
 'LVM201000064250',
 'HP22-21670',
 'NLPD200630010584',
 'LVM210200030906',
 '2208-066572',
 'NLPD2205120008698',
 'LVM190900142747',
 'LVM230400055512',
 'RPDRP23-5299',
 'LVM190800032120',
 'RPD21-18020',
 'LVM221000055155',
 'LVM210600012645',
 'LVM190700087922',
 'RPD21-24431',
 'LVM191000140614',
 'LVM210400064023',
 'LVM200400038077',
 'LVM200100123440',
 'RPD22-14342',
 'LVM190700013859',
 'NLPD1908060016038',
 'RPDRP20-10923',
 'LVM230300118127',
 'RPD23-16066',
 'NHP231200576',
 'FAPDTA21-0120',
 'LVM191100040084',
 'LVM231100031023',
 'LVM220200076072',
 'NLPD2011080018539',
 'LVM220300002949',
 'LVM230700033044',
 'LVM210500033976',
 'LVM201100095710',
 'LVM200200073220',
 'LVM190800011947',
 'RPD20-13675',
 'LVM220400021235',
 'LVM220500127221',
 'LVM220100021463',
 'NLPD230202002289',
 'LVM220100107103',
 'SPPD21-1689',
 'LVM231200015686',
 'LVM201100129146',
 'HP21-20560',
 'LVM220200013198',
 'LVM210300059312',
 'LVM221200035934',
 'LVM220100023948',
 'LVM231200103861',
 'NLPD21030200000006',
 'RPD22-20034',
 'RPD23-10143',
 'LVM221200005416',
 'LVM221100011017',
 'RPD23-21347',
 'RPD23-12122',
 'LVM200400087450',
 'NHP230601330',
 'LVM220800034067',
 'RPD23-21957',
 'NLPD2201020000081',
 'NLPD2309090018113',
 'LVM211000109305',
 'LVM211000008625',
 'LVM190300073654',
 'RPD19-8363',
 'LVM191100082308',
 'RPD19-17613',
 'HP22-01570',
 'LVM220300033196',
 'RPD21-20613',
 'HP19-06721',
 'LVM190100034646',
 'RPD21-16044',
 'NLPD1905030009187',
 'LVM201200093720',
 'RPD20-1572',
 'LVM231100045620',
 'LVM230300118182',
 'SPPD23-6364',
 'HP20-11523',
 'LVM200100052770',
 'LVM231100034508',
 'LVM190400126384',
 'LVM210900066447',
 'WWPD202300007180',
 'LVM211100059856',
 'NLPD2005080007722',
 'ELPD2020-24873',
 'NLPD2103220004883',
 'NHP190602100',
 'NHP220701029',
 'LVM220800034253',
 'LVM220400049959',
 'RPD20-4250',
 'LVM221000090751',
 'NLPD2303090004801',
 'RPD19-23199',
 'LVM220100116535',
 'LVM190900131075',
 'HP20-02625',
 'LVM220600049020',
 'LVM191100128931',
 'LVM230600091917',
 'LVM230400110243',
 'NHP220901967',
 'RPD23-21740',
 'SPPD23-7287',
 'RPD21-17753',
 'LVM211200065189',
 'LVM190600001981',
 'LVM210700076321',
 'LVM190700040463',
 'NLPD2210070019125',
 'LVM221000096878',
 'LVM230100095891',
 'LVM230100044561',
 'LVM221100030842',
 'LVM200800006264',
 'NHP220401731',
 'NHP200900651',
 'NLPD1912090025431',
 'LVM200600003765',
 'LVM210100037645',
 'RPD21-5841',
 'RPD21-4665',
 'NYSO23NY-3083',
 'LVM220500070639',
 'YPD21YE-0004',
 'LVM231200010351',
 'LVM231100045257',
 'SPPD19-891',
 'NHP230600569',
 'LVM190700111980',
 'LVM210800124597',
 'NHP230200613',
 'LVM221200063066',
 'RPD19-17078',
 'NLPD22052600009697',
 'RPD22-22811',
 'LVM211200000741',
 'LVM220200003220',
 'LVM230500002250',
 'RPD21-20404',
 'LVM231000002019',
 'LVM190900008725',
 'LVM200900071596',
 'ELPD2022-04720',
 'LVM230100082531',
 'NLPD2310130020548',
 'NHP230701384',
 'LVM210600134693',
 'RPD21-1627',
 'LVM210700043434',
 'NLPD2009090014865',
 'LVM231000071147',
 'LVM230800063214',
 'LVM200900103091',
 'LVM230700117581',
 'LVM230300023270',
 'LVM220100037056',
 'RPD20-20404',
 'RPD19-14100',
 'LVM210400024094',
 'LVM220400114673',
 'HP21-02605',
 'LVM200800083699',
 'NYSO23NY-3722',
 'RPD19-108179',
 'LVM201200077786',
 'NLPD2106190010280',
 'HP21-06581',
 'LVM200800038294',
 'LVM221000077486',
 'LVM211100032906',
 'LVM221100018373',
 'LVM190500053767',
 'LVM200800134771',
 'LVM211000047349',
 'RPD22-3750',
 'LVM190500125254',
 'LVM190400041767',
 'LVM221000039355',
 'LVM190900004512',
 'LVM210500047184',
 'LVM200100037534',
 'LVM231100092403',
 'LVM210600109810',
 'LVM220200110386',
 'LVM220100047029',
 'LVM191100060313',
 'RPD19-24062',
 'LVM210200117254',
 'LVM190500137253',
 'LVM210100053151',
 'LVM231000013314',
 'LVM211000041154',
 'LVM190100051748',
 'SPPD20-9721',
 'NLPD2107240012546',
 'NLPD2202150002858',
 'RPD23-2950',
 'LVM190200059579',
 'LVM230100084443',
 'NLPD2306070011554',
 'NYSO21NY-0426',
 'NHP221002028',
 'SPPD19-10148',
 'LVM230900052187',
 'LVM190300129144',
 'LVM210900047237',
 'NHP191202225',
 'LVM211100015603',
 'ELPD23EP-3038',
 'RPD22-12331',
 'LVM200200121036',
 'LVM211000111979',
 'LVM200500089939',
 'LVM211000003129',
 'LVM201000096148',
 'LVM230200038211',
 'LVM200400135981',
 'LVM230900052164',
 'LVM220300116731',
 'LVM220200011352',
 'NHP230501392',
 'RPD23-10421',
 'LVM190900124548',
 'LVM230400134956',
 'LVM200800076833',
 'NHP221200348',
 'LVM220200003496',
 'NLPD1907030013686',
 'LVM220100017135',
 'WASO20-5343',
 'LVM200800049071',
 'LVM221100036931',
 'HP19-20620',
 'LVM201100103133',
 'LVM211100091991',
 'NLPD19050400009264',
 'LVM210200088519',
 'LVM201200067964',
 'LVM190600103849',
 'LVM220100103609',
 'LVM230600022045',
 'LVM220700088667',
 'RPD20-17311',
 'LVM190500108112',
 'LVM230900035270',
 'HP19-30161',
 'RPD20-15538',
 'LVM231100024323',
 'LVM231200032848',
 'NHP220901073',
 'NLPD2303270006052',
 'SPPD19-10760',
 'LVM210700070276',
 'LVM190900009058',
 'NHP210200793',
 'LVM190100019000',
 'LVM200500029963',
 'LVM190700118831',
 'LVM220400002063',
 ...}

In [30]:
sorted(sheet_crashes_no_dup.columns)

['AgencyName',
 'AlcoholInvolved',
 'AreaOfInitialImpact',
 'ArrivedDate',
 'ArrivedTime',
 'Beat',
 'City',
 'County',
 'CountyLocated',
 'CrashDate',
 'CrashNum',
 'CrashSeverity',
 'CrashTime',
 'CrashType',
 'DirFromLandmark',
 'DirFromLandmarkLocated',
 'DistFromLandmark',
 'DistFromLandmarkLocated',
 'DistLandmarkApprox',
 'FirstHarmfulEventDesc',
 'HitandRun',
 'IncidentClearanceTime',
 'Intersection',
 'LandmarkUnit',
 'LightCondition',
 'LightConditionOther',
 'Location',
 'LocationFirstEvent',
 'LocationFirstEventOther',
 'LocationFirstEventTrav',
 'LocationFirstEventTurn',
 'Measure',
 'MilePost',
 'MotorcycleInvolved',
 'NotifiedDate',
 'NotifiedTime',
 'NumFatalities',
 'NumInjured',
 'NumNonMotorists',
 'NumOccupants',
 'NumRestrained',
 'NumVehicles',
 'OfficeReport',
 'OutsideTown',
 'PedestrianInvolved',
 'PrivateProperty',
 'PropertyDamage',
 'PropertyDamageDesc',
 'ReportComplete',
 'ReportDate',
 'RoadEnvironFactorsOtherEnv',
 'RoadEnvironFactorsOtherHwy',
 'RoadEnvironmentalFactors',
 'RoadIntersectType',
 'RoadIntersectTypeOther',
 'RoadPaddleMarkers',
 'RoadSurface',
 'RoadSurfaceOther',
 'RoadwayClearanceTime',
 'RouteID',
 'SchoolZone',
 'SecondaryCollision',
 'Street1',
 'Street1Located',
 'Street1Other',
 'Street2',
 'Street2Located',
 'Street2Other',
 'TrafficControlOther',
 'VehCrashType',
 'Weather',
 'WeatherOther',
 'X',
 'Y']

In [31]:
# Filter and extract data
columns_extract_crashes = [
    'CrashNum',
    'Street1',
    'Street1Other',
    'Street1Located',
    'Street2',
    'Street2Other',
    'Street2Located',
    'CrashDate',
    'CrashTime',
    'City',
    'County',
    'CountyLocated',
    'X',
    'Y',
]
sheet_crashes_pedestrian = sheet_crashes_no_dup.filter(pl.col('CrashNum').is_in(crash_nums_pedestrian))[:, columns_extract_crashes]
sheet_crashes_pedestrian

shape: (4_972, 14)
┌────────────┬────────────┬────────────┬───────────┬───┬────────┬───────────┬───────────┬──────────┐
│ CrashNum   ┆ Street1    ┆ Street1Oth ┆ Street1Lo ┆ … ┆ County ┆ CountyLoc ┆ X         ┆ Y        │
│ ---        ┆ ---        ┆ er         ┆ cated     ┆   ┆ ---    ┆ ated      ┆ ---       ┆ ---      │
│ str        ┆ str        ┆ ---        ┆ ---       ┆   ┆ str    ┆ ---       ┆ f64       ┆ f64      │
│            ┆            ┆ str        ┆ str       ┆   ┆        ┆ str       ┆           ┆          │
╞════════════╪════════════╪════════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪══════════╡
│ RPD23-6918 ┆ NORTH      ┆ null       ┆ NORTH     ┆ … ┆ WASHOE ┆ WASHOE    ┆ 256127.49 ┆ 4.3877e6 │
│            ┆ HILLS BLVD ┆            ┆ HILLS     ┆   ┆        ┆           ┆ 65        ┆          │
│            ┆            ┆            ┆ BLVD      ┆   ┆        ┆           ┆           ┆          │
│ LVM1907000 ┆ S BRUCE ST ┆ null       ┆ S BRUCE   ┆ … ┆ CLARK  ┆ CLARK     ┆ 668657.22 ┆ 4.0032e6 │
│ 07066      ┆            ┆            ┆ ST        ┆   ┆        ┆           ┆ 55        ┆          │
│ CCSO21-792 ┆ N STEWART  ┆ null       ┆ N STEWART ┆ … ┆ CARSON ┆ CARSON    ┆ 261167.42 ┆ 4.3390e6 │
│ 7          ┆ ST         ┆            ┆ ST        ┆   ┆ CITY   ┆ CITY      ┆ 69        ┆          │
│ LVM2111000 ┆ W CRAIG RD ┆ null       ┆ W CRAIG   ┆ … ┆ CLARK  ┆ CLARK     ┆ 658062.32 ┆ 4.0120e6 │
│ 36560      ┆            ┆            ┆ RD        ┆   ┆        ┆           ┆ 95        ┆          │
│ NHP2201015 ┆ SR372      ┆ null       ┆ SR372     ┆ … ┆ NYE    ┆ NYE       ┆ 590697.80 ┆ 4.0073e6 │
│ 74         ┆            ┆            ┆           ┆   ┆        ┆           ┆ 4         ┆          │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …        │
│ HP21-02090 ┆ ST ROSE    ┆ null       ┆ ST ROSE   ┆ … ┆ CLARK  ┆ CLARK     ┆ 668408.00 ┆ 3.9850e6 │
│            ┆ PKWY       ┆            ┆ PKWY      ┆   ┆        ┆           ┆ 21        ┆          │
│ LVM2203000 ┆ E HARMON   ┆ null       ┆ E HARMON  ┆ … ┆ CLARK  ┆ CLARK     ┆ 664925.35 ┆ 3.9975e6 │
│ 46344      ┆ AVE        ┆            ┆ AVE       ┆   ┆        ┆           ┆ 28        ┆          │
│ NLPD190720 ┆ E CAREY    ┆ null       ┆ E CAREY   ┆ … ┆ CLARK  ┆ CLARK     ┆ 669188.52 ┆ 4.0081e6 │
│ 0014915    ┆ AVE        ┆            ┆ AVE       ┆   ┆        ┆           ┆ 96        ┆          │
│ SPPD22-804 ┆ C ST       ┆ null       ┆ C ST      ┆ … ┆ WASHOE ┆ WASHOE    ┆ 261958.88 ┆ 4.3799e6 │
│ 4          ┆            ┆            ┆           ┆   ┆        ┆           ┆ 17        ┆          │
│ NLPD220329 ┆ SIMMONS ST ┆ null       ┆ SIMMONS   ┆ … ┆ CLARK  ┆ CLARK     ┆ 663520.83 ┆ 4.0129e6 │
│ 0005653    ┆            ┆            ┆ ST        ┆   ┆        ┆           ┆ 47        ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴────────┴───────────┴───────────┴──────────┘

## Extract Bicyclist Data

In [32]:
# Get crash numbers
any_pedal_cyclist = (pl.col('PersonType') == 'Pedal Cyclist').any()
crash_nums_bicyclist = set(group_by.agg(any_pedal_cyclist).filter(pl.col('PersonType'))[:, 'CrashNum'])
crash_nums_bicyclist

{'LVM200500045594',
 'LVM230900087323',
 'WASO21-3153',
 'RPD23-4665',
 'LVM231000037631',
 'FAPDTA19-0063',
 'LVM220300049695',
 'LVM200100016962',
 'LVM191000112151',
 'LVM221000103802',
 'SPPD23-4209',
 'NHP210501221',
 'LVM230800087029',
 'RPD20-7291',
 'RPD21-8137',
 'LVM220700065076',
 'HP19-19036',
 'RPD21-9796',
 'HP21-20884',
 'NLPD2109020015018',
 'LVM220200086266',
 'LVM201000117476',
 'LVM190400036283',
 'LVM210600119896',
 'NHP200600419',
 'LVM191000051600',
 'NHP211101500',
 'RPD20-14070',
 'RPD23-17265',
 'SPPD23-7662',
 'LVM211100083173',
 'RPD22-14183',
 'LVM210200024550',
 'NLPD2302070002620',
 'LVM220900034982',
 'RPD20-11764',
 'LVM230500048561',
 'NLPD2309200018806',
 'LVM191200022327',
 'RPD19-17656',
 'LVM190500003879',
 'LVM220500099215',
 'HP20-13121',
 'LVM210700003340',
 'ELPD2019-21546',
 'LVM200700093565',
 'CHSOC20-05990',
 'HP22-15090',
 'LVM211100001832',
 'WPSO2107140030',
 'CCSO23-5255',
 'RPD19-19955',
 'RPD20-16776',
 'CCSO21-5716',
 'LVM190500146418',
 'CCSO22-4866',
 'RPD21-7427',
 'NHP230800972',
 'SPPD20-1617',
 'SPPD19-6925',
 'LVM221200010568',
 'CLSD23035151',
 'BCPD22BC0593',
 'LVM200100063765',
 'NHP221101152',
 'LVM231100060076',
 'SPPD21-7671',
 'HP20-19796',
 'SPPD22-3755',
 'LVM200600075302',
 'LVM190900121381',
 'NLPD1902250004012',
 'NLPD2110010016955',
 'LVM210300042018',
 'LVM231100059666',
 'LVM230200051451',
 'LVM210900100167',
 'LVM220600055415',
 'NLPD1901180001273',
 'LVM220800105595',
 'RPD19-2622',
 'MSPD210502-10',
 'LVM221000099983',
 'LVM230700125056',
 'LVM231200076684',
 'LVM220200107045',
 'NHP211101399',
 'LVM210800115790',
 'LVM201000003121',
 'HP23-06013',
 'LVM221100023824',
 'RPD19-10895',
 'LVM210400126293',
 'SPPD19-7261',
 'LVM210200002605',
 'RPD22-18703',
 'NHP231100965',
 'LVM190100068968',
 'LVM190100102841',
 'LVM220600062348',
 'LVM210100084350',
 'NLPD2305080009210',
 'ELPD23EP12145',
 'LVM220500028310',
 'SPPD23-2871',
 'NYSO21NY-1180',
 'RPD20-7389',
 'RPD19-20122',
 'RPD19-18472',
 'SPPD21-5562',
 'LVM190300033444',
 'NHP210200386',
 'SPPD20-3554',
 'LVM220300050757',
 'NHP210200759',
 'CLSD230246070',
 'HP19-30256',
 'LVM191000110054',
 'HP23-11577',
 'RPD23-7637',
 'LVM220300116644',
 'RPD22-6625',
 'NLPD2103210004827',
 'RPD23-11602',
 'LVM200900041597',
 'LVM200900075948',
 'LVM210200103866',
 'LVM230600021713',
 'RPD22-12406',
 'LVM230300048225',
 'LVM200900058865',
 'LVM221100014792',
 'NHP200101423',
 'LVM220900011223',
 'RPD22-4391',
 'DCSO20SO15435',
 'LVM230900069819',
 'LVM221100083260',
 'WNPD21-0571',
 'LVM230200025194',
 'LYSO22LY03864',
 'RPD20-18873',
 'SPPD21-10718',
 'NHP210100622',
 'LVM230500115919',
 'RPD21-14865',
 'NLPD2310310021846',
 'HP23-01126',
 'RPD19-10465',
 'SPPD23-8186',
 'SPPD21-3512',
 'LVM190500101158',
 'LVM191000051553',
 'NLPD1910080020462',
 'CCSO23-0626',
 'LVM210600039551',
 'LVM220300065422',
 'LVM201100014981',
 'LVM210500111936',
 'LVM210400009056',
 'HP22-11886',
 'RPD20-11576',
 'LVM200900102440',
 'LVM200400096716',
 'LVM221200050526',
 'RPD19-5143',
 'LVM211000066965',
 'RPD23-107428',
 'LVM230400076692',
 'NLPD2307060013580',
 'LVM230500080425',
 'LVM210700135060',
 'LVM191000025116',
 'HP22-17785',
 'NHP190601860',
 'LVM200200121600',
 'CLSD22095353',
 'LVM190100040646',
 'ELPD2021-05837',
 'LVM210100135849',
 'BCPD22BC0946',
 'LVM230900015204',
 'LVM220500098457',
 'LVM190800126953',
 'HP22-04212',
 'CCSO19-05753',
 'LVM201200063119',
 'SPPD22-1140',
 'SPPD23-4508',
 'HP23-26751',
 'HP21-21814',
 'SPPD22-7568',
 'CCSO22-496',
 'LVM190100009093',
 'LVM220500021954',
 'NHP200900189',
 'NHP201100922',
 'LVM210400130607',
 'HP23-15171',
 'NHP190301358',
 'RPD20-1177',
 'LVM210700089508',
 'LVM190500085979',
 'LVM190900073661',
 'LVM200900048572',
 'RPD20-110246',
 'LVM210300002985',
 'LVM190600046853',
 'LVM200500074645',
 'LVM191000035795',
 'RPD20-6173',
 'HP21-17527',
 'LVM211000001971',
 'NHP200901153',
 'LVM230500025448',
 'ELPD2022-08306',
 'NLPD210126001573',
 'HP20-14039',
 'LVM200700030276',
 'LVM221000103407',
 'LVM190800027052',
 'LVM220600117888',
 'RPD21-20773',
 'LVM201000008139',
 'LVM190300046216',
 'NHP210701417',
 'LVM210200078632',
 'LVM230100054818',
 'HP23-06846',
 'LVM200800018418',
 'HP23-23043',
 'NLPD2201050000252',
 'HP21-12831',
 'HP22-06814',
 'LVM220300064032',
 'RPD23-5670',
 'HP23-24397',
 'LVM200400057117',
 'NLPD1904070007174',
 'LVM190100054015',
 'RPD21-17138',
 'MSPD201010-11',
 'NLPD2204230007443',
 'CHSOC22-03638',
 'LVM221100012917',
 'RPD19-22816',
 'LVM230700002019',
 'LVM230900056742',
 'LVM200200004274',
 'SPPD20-2264',
 'RPD19-13277',
 'LVM221000037169',
 'LVM190200021735',
 'LVM221200066481',
 'LVM190700133433',
 'HP19-18484',
 'RPD22-10647',
 'NLPD2309160018592',
 'LVM200700107254',
 'LVM200100093139',
 'LVM210100045026',
 'RPD23-11537',
 'RPD20-18240',
 'BCPD22BC1170',
 'LVM200500027079',
 'LVM230700131186',
 'LVM210400034737',
 'RPD22-21410',
 'LVM201000136176',
 'RPD20-3716',
 'LVM190600032982',
 'CLSD23087781',
 'NHP230101983',
 'LVM220300116775',
 'NLPD2205180009040',
 'NHP201000041',
 'LVM211100073956',
 'NYSO21NY-2818',
 'LVM231100013183',
 'HP19-15482',
 'CCSO21-3047',
 'LVM191200091868',
 'BCPD23BC0649',
 'LVM221000092841',
 'HP23-12142',
 'NHP210802118',
 'NLPD1910100020582',
 'LVM220300116335',
 'LVM210600000918',
 'LVM220500006350',
 'RPD19-20578',
 'RPD23-12741',
 'LVM230900009046',
 'LVM191200084173',
 'CCSO23-2738',
 'RPD23-16715',
 'NHP220201605',
 'LVM221000104832',
 'LVM190900097725',
 'LVM190800137943',
 'NLPD2304010006416',
 'LVM230800061032',
 'LVM190400022457',
 'SPPD22-6652',
 'RPD23-23401',
 'LVM230700066144',
 'HP23-16962',
 'LVM210600114337',
 'LVM191100001112',
 'NHP190800438',
 'LVM210200056949',
 'LVM190800074940',
 'LVM201100048310',
 'LVM230100123433',
 'HP22-14447',
 'LVM230600103257',
 'LVM201200098940',
 'LVM220900032482',
 'LVM220500047973',
 'HP19-22084',
 'LVM231200071471',
 'RPD19-6782',
 'SPPD23-4405',
 'NLPD22010070019172',
 'LVM210800115107',
 'HP23-16416',
 'NLPD2001280001903',
 'NHP201002092',
 'LVM190600085761',
 'LVM230400090968',
 'CCSO20-6303',
 'CLSD20009557',
 'LVM230600040813',
 'LVM200100085814',
 'LVM231000080630',
 'LVM221000103179',
 'SPPD22-9602',
 'RPD20-106132',
 'LVM190300021249',
 'NHP190701225',
 'NLPD2309060017909',
 'RPD19-9624',
 'LVM230900051091',
 'RPD22-1814',
 'LVM190400011197',
 'HP23-03161',
 'SPPD20-445',
 'CLSD19137067',
 'LVM230900049302',
 'HP19-08296',
 'CHSOC23-04804',
 'LVM210100052694',
 'LVM230500013116',
 'NHP200400680',
 'LVM221100040203',
 'HP21-17736',
 'NHP190600038',
 'SPPD20-7389',
 'RPD22-10637',
 'LVM190600097439',
 'RPD20-7574',
 'SPPD21-6892',
 'LVM201200117491',
 'LVM211200066808',
 'HP20-14216',
 'LVM210300044452',
 'LVM191000137667',
 'LVM200600122644',
 'RPD22-19123',
 'SPPD20-3097',
 'LVM220700001761',
 'LVM220200015655',
 'LVM221100085412',
 'HP19-21770',
 'LVM210100040771',
 'NLPD2104070005776',
 'NLPD2007220011845',
 'LVM231200067288',
 'RPD23-10000',
 'NLPD2210200020025',
 'NLPD2104300007168',
 'LVM200800020531',
 'LVM231000096217',
 'LVM201100022395',
 'SPPD19-5229',
 'LVM200600055487',
 'CLSD20014221',
 'RPD22-17628',
 'HP21-21786',
 'ELPD2021-11041',
 'HP20-01073',
 'LVM220600037993',
 'LVM190800011607',
 'LVM221200070555',
 'RPD19-21732',
 'LVM210900124423',
 'LVM190900080987',
 'HP21-00888',
 'LVM230800104967',
 'NHP200400442',
 'LVM201000126950',
 'LVM190400032763',
 'NLPD2210210020141',
 'LVM190500003764',
 'LVM200400097267',
 'LVM220700115430',
 'LVM231000084189',
 'HP19-04956',
 'LVM190900093384',
 'NHP211001805',
 'LVM190800147404',
 'LVM210900120527',
 'LVM230900081581',
 'LVM190400011182',
 'LVM220800024038',
 'LVM210500038516',
 'HP21-02578',
 'LVM231000075194',
 'NHP210801716',
 'LVM210700053966',
 'NHP220701770',
 'LVM220800121306',
 'NLPD2205020008029',
 'NLPD2211170021941',
 'RPD19-20341',
 'LVM230400046491',
 'HP20-03566',
 'LVM211000012032',
 'LVM231000058056',
 'LVM210600130316',
 'LVM220200053439',
 'LVM230900084983',
 'LVM220200062569',
 'LVM230800104828',
 'LVM200400115920',
 'LVM220800083928',
 'LVM230200073167',
 'RPD21-2338',
 'LVM220100074586',
 'LVM191100133022',
 'LVM210900066318',
 'HP23-10749',
 'LVM190500084026',
 'RPD19-16564',
 'LVM221100065630',
 'LVM230300125380',
 'LVM230300101307',
 'MSPDMPPD230109041',
 'CCSO2020-6399',
 'LVM221100006170',
 'HP23-23563',
 'NLPD2106210010417',
 'LVM220400092975',
 'LVM220200075261',
 'LVM190900055383',
 'NLPD2210070019149',
 'LVM230400068054',
 'SPPD20-4079',
 'SPPD21-6128',
 'NHP221200386',
 'LVM220900073484',
 'LVM190300111661',
 'NLPD2105210008503',
 'LVM220900110215',
 'RPD23-20862',
 'HP23-17896',
 'NHP210501987',
 'LVM211000123610',
 'LVM210700118084',
 'LVM210800081159',
 'LVM191000086118',
 'LVM190500002303',
 'LVM191100007538',
 'LVM200200126966',
 'RPD19-15630',
 'NLPD2309060017845',
 'FAPDTA19-0025',
 'HP23-18137',
 'LVM190700066905',
 'HP23-09364',
 'LVM210700127378',
 'LVM211000063045',
 'NLPD2104080005880',
 'HP20-11597',
 'RPD19-107678',
 'HP23-09507',
 'LVM190300081595',
 'LVM201100119980',
 'LVM191200083468',
 'LVM230400108411',
 'HP19-05008',
 'LVM210400132076',
 'RPD22-19180',
 'LVM230600071007',
 'LVM211100005988',
 'LVM190900109661',
 'LVM210600036588',
 'LVM220500076562',
 'LVM210500021567',
 'HP23-18672',
 'NHP230300677',
 'NLPD2006180009994',
 'LVM220100020017',
 'NHP210700447',
 'LVM230400046292',
 'LVM200500074832',
 'NHP220400073',
 'LVM230300100924',
 'LVM230800014205',
 'LVM221100108360',
 'LVM190500148209',
 'HP22-16409',
 'HP23-18523',
 'LVM220300107579',
 'RPD19-7326',
 'RPD22-17653',
 'NLPD2211070021265',
 'NLPD1910220021354',
 'LVM190300099478',
 'LVM211200047938',
 'RPD19-25123',
 'LVM210400097722',
 'HP20-06557',
 'LVM200900060857',
 'NHP210800386',
 'LVM190700124810',
 'RPD19-19344',
 'HP21-19978',
 'NHP200500011',
 'NHP200202195',
 'SPPD21-4579',
 'LVM190900029820',
 'RPD19-17800',
 'HP22-10196',
 'LVM210200070033',
 'LVM200200032672',
 'LVM230600003133',
 'RPD23-13594',
 'LVM210800121341',
 'NHP230100520',
 'LVM230800065010',
 'NHP210502309',
 'RPD20-16454',
 'LVM220300086695',
 'NLPD2209240018221',
 'RPD23-18126',
 'LVM200600110928',
 'LVM230400079349',
 'LVM191000119072',
 'HP20-18176',
 'HP23-02433',
 'HP20-14436',
 'LVM230800023615',
 'WASO19-2419',
 'LVM230800007035',
 'LVM221200091910',
 'LVM230600125568',
 'LVM220500075932',
 'SPPD22-8580',
 'HP23-11683',
 'LVM210500003581',
 'LVM230500009009',
 'NLPD2007190011698',
 'LVM210100035552',
 'LVM191000119009',
 'RPD23-4582',
 'LVM190100018663',
 'WASO19-2177',
 'NHP220400475',
 'HP22-04197',
 'NLPD2209030016673',
 'LVM210900098481',
 'LVM220200061927',
 'LVM200200016697',
 'NLPD2308220016796',
 'NLPD2110140019617',
 'HP20-16609',
 'NLPD2309230019077',
 'LVM230500136103',
 'LVM210800116127',
 'WASO21-285',
 'RPD23-15344',
 'NHP221000298',
 'MSPD191224-07',
 'LVM220200068833',
 'LVM190900062476',
 'LVM220300096423',
 'LVM230100091723',
 'LVM191000064396',
 'NLPD2012310021529',
 'LVM191000112305',
 'NLPD2304030006547',
 'RPD22-12612',
 'NHP210400069',
 'LVM201100089790',
 'NLPD2201050000297',
 'LVM230800059733',
 'NHP210901003',
 'LVM220700085000',
 'RPD19-10572',
 'HP22-15561',
 'WASD21W-01038',
 'LVM230600080730',
 'RPD19-8838',
 'NHP210801588',
 'LVM220600003870',
 'LVM220200103134',
 'RPD19-17195',
 'SPPD23-5670',
 'LVM201000033673',
 'NLPD1906260013194',
 'LVM221000025416',
 'LVM220100016340',
 'NHP210100157',
 'CLSD23098520',
 'LVM190800020337',
 'LVM210500065702',
 'LVM220600066694',
 'NLPD2206140010911',
 'NLPD1907170014746',
 'LVM230600050504',
 'LVM221000008671',
 'LVM210500048260',
 'LVM210900073604',
 'LVM200200114186',
 'LVM191100036339',
 'LVM200500082946',
 'HP19-06890',
 'LVM201000128881',
 'LVM210500014829',
 'LVM220300035134',
 'LVM201100067287',
 'LVM200400041101',
 'NLPD2109130015744',
 'HP22-19360',
 'LVM220400090781',
 'RPD23-10076',
 'LVM200100075462',
 'LVM201000104264',
 'LVM210100110246',
 'STSO19-584',
 'LVM221100078739',
 'LVM220200005764',
 'LVM210600135597',
 'RPD21-19952',
 'NLPD2011060018455',
 'CCSO19-5756',
 'LVM190800097689',
 'LVM210800054420',
 'RPD23-12507',
 'HP23-25250',
 'SPPD23-9676',
 'LVM221200002454',
 'HP22-14018',
 'NLPD1911070022385',
 'LVM200700131564',
 'LVM190700109574',
 'LVM230700121545',
 'NLPD1908280017576',
 'RPD20-18993',
 'RPD20-14313',
 'LVM231000096206',
 'LVM200500046789',
 'LVM211000084448',
 'FAPDTA23-0107',
 'LVM221000090889',
 'RPD21-5058',
 'LVM210800111222',
 'LVM220600032509',
 'LVM230500124735',
 'HP19-07966',
 'SPPD19-5263',
 'SPPD20-7643',
 'HP19-17809',
 'NHP210901228',
 'LVM191200045612',
 'LVM210800115250',
 'LVM200200073365',
 'NLPD2202240003447',
 'LVM220600008995',
 'LVM220800081882',
 'LVM210900086232',
 'RPD21-8349',
 'LVM190500079278',
 'LVM220500020231',
 'LVM230900045046',
 'HP20-20715',
 'LVM191100065216',
 'NLPD2211140021706',
 'RPD22-8240',
 'LYSO21LY01687',
 'SPPD22-6950',
 'LVM220400106496',
 'LVM210700100562',
 'LVM230800108243',
 'CLSD23087001',
 'RPD22-18330',
 'LVM230100037488',
 'LVM191100007575',
 'BCPD23BC0844',
 'LVM231200077385',
 'NLPD1910260021576',
 'NLPD2212250024270',
 'LVM200300077349',
 'LVM191200011622',
 'RPD22-13407',
 'NLPD1904040007021',
 'LVM201000085795',
 'SPPD20-2493',
 'LVM200900082289',
 'LVM200500141289',
 'NYSO19NY-4035',
 'NYSO23NY-1223',
 'NLPD2005180008253',
 'CCSO20-6981',
 'LVM210300088704',
 'RPD19-13536',
 'RPD20-17156',
 'NLPD2304200007886',
 'LVM210600109152',
 'LVM201100106372',
 'NHP211101495',
 'NHP230700998',
 'NLPD2212290024562',
 'LVM190400048299',
 'LVM210200025180',
 'RPD20-14174',
 'LVM210800046498',
 'NLPD2101030000128',
 'LVM211000111324',
 'HP20-14746',
 'LVM230700003986',
 'LVM230900048681',
 'LVM221100086805',
 'LVM201000064454',
 'LVM190200086813',
 'LVM220200031646',
 'RPD22-17938',
 'HP23-22628',
 'SPPD20-3058',
 'LVM200200076723',
 'RPD21-4501',
 'SPPD23-3684',
 'HP23-19161',
 'HP22-04106',
 'MSPD190329-06',
 'LVM230500110648',
 'RPD19-10228',
 'RPD21-13841',
 'LVM230100017688',
 'LVM210600117021',
 'NHP211000667',
 'LVM191200082913',
 'LVM220900076873',
 'LVM200400099478',
 'LVM230500063601',
 'RPD23-15265',
 'LVM190100136970',
 'LVM200800070916',
 'LVM220700071333',
 'LVM210100002790',
 'LVM191200046495',
 'LVM190900094499',
 'LVM220500084747',
 'LVM231100002469',
 'NHP230700352',
 'LVM210900095788',
 'SPPD20-4246',
 'LVM220800019403',
 'SPPD23-4101',
 'NLPD2211210022189',
 'LVM210800090954',
 'HP22-06641',
 'LVM200200116028',
 'LVM210300110855',
 'LVM231000086135',
 'LVM190400108121',
 'LVM211200123209',
 'RPD22-7288',
 'NLPD2208030014388',
 'HP19-02576',
 'LVM211200009639',
 'LVM200100012625',
 'SPPD19-10489',
 'LVM230800049834',
 'LVM230500008556',
 'HP22-22176',
 'NLPD191119023222',
 'HP19-01786',
 'LYSO19LY02935',
 'LVM200900007088',
 'LVM200200105621',
 'HP21-06646',
 'NLPD2302180003424',
 'LVM211000054530',
 'LVM220400011123',
 'NYSO20NY-4464',
 'LVM220800101508',
 'LVM230100095624',
 'LVM191100026919',
 'RPD22-19769',
 'NHP220600724',
 'LVM211200028084',
 'LVM191200026533',
 'RPD19-12309',
 'NLPD2105230008623',
 'SPPD22-7535',
 'LVM190500153426',
 'NHP210801218',
 'NHP201201356',
 'HP20-16289',
 'NYSO22NY-4504',
 'SPPD19-2506',
 'HP22-15191',
 'LVM221000069249',
 'LVM191100067819',
 'NLPD1901100000705',
 'SPPD19-8991',
 'LVM190800128853',
 'LVM220300112166',
 'RPD22-17851',
 'LVM211100097631',
 'LVM220700079287',
 'RPD21-6270',
 'NHP200700473',
 'LVM190700102237',
 'LVM190300099583',
 'LVM201000128555',
 'LVM230400042587',
 'LVM220600009175',
 'LVM230500097940',
 'LVM210800002990',
 'LVM200800046680',
 'NHP210900925',
 'LVM220700114607',
 'LVM230400010210',
 'NLPD1909140018782',
 'LVM190900143591',
 'NYSO21NY-4967',
 'LVM201000115232',
 'LVM221000119900',
 'NLPD2207250013751',
 'RPD20-6284',
 'RPD21-17113',
 'LVM210300135688',
 'LVM200800044533',
 'LVM230300047463',
 'LVM210500070034',
 'LVM231100060991',
 'SPPD19-5431',
 'HP20-12979',
 'HP22-09207',
 'LVM220100108582',
 'LVM210600066110',
 'NLPD1909270019696',
 'LVM231000080657',
 'LVM190100063086',
 'LVM211000091156',
 'LVM231100088145',
 'NLPD2302040002403',
 'RPD22-22503',
 'RPD21-5567',
 'LVM191100092038',
 'SPPD21-2842',
 'NLPD2110070017323',
 'LVM220100086036',
 'NHP220901774',
 'LVM201000113601',
 'LVM211200113254',
 'LVM221100014187',
 'LVM201000043025',
 'LVM190800061742',
 'LVM211100093956',
 'LVM200900008374',
 'CLSD22124441',
 'LVM220400049683',
 'LVM190300017373',
 'LVM220100070450',
 'NLPD1904250008521',
 'HP22-18530',
 'NHP190102249',
 'NLPD2209280018499',
 'LVM191000068124',
 'LVM221000073032',
 'LVM210500112350',
 'LVM210300007817',
 'LVM200500042815',
 'NHP190500840',
 'LVM190500002746',
 'HP23-12112',
 'HP23-20527',
 'NLPD2010280017885',
 'LVM190500013932',
 'LVM210400134687',
 'HP21-03294',
 'LVM200500092828',
 'NHP190900906',
 'RPD20-613',
 'NLPD2111110019649',
 'LVM211100039204',
 'LVMLLV220800052083',
 'LVM200800112493',
 'LVM230900053565',
 'LVM220400118592',
 'LVM220300124887',
 'CLSD22081979',
 'LVM211200027466',
 'LVM220100050496',
 'LVM220500095998',
 'LVM220900090449',
 'LVM230500081551',
 'LVM230600036011',
 'RPD19-19853',
 'NHP230201665',
 'LVM231000082916',
 'HP22-13546',
 'NLPD2001070000406',
 'LVM211200011045',
 'SPPD21-4427',
 'LVM200800082735',
 'LVM190200050104',
 'NLPD2004210006866',
 'RPD21-14159',
 'LVM231200081555',
 'CLSD23027681',
 'LVM230900042658',
 'LVM201200092660',
 'WASO21-4140',
 'LVM210100046069',
 'LVMLLV221000029497',
 'LVM191200070488',
 'NHP200400781',
 'LVM200600114852',
 'RPD19-13458',
 'NLPD2306140012098',
 'CCSO23-5591',
 'BCPD19BC1316',
 'NHP210900458',
 'LVM201000001385',
 'LVM210500064618',
 'LVM210300001603',
 'ELPD2019-25785',
 'LVM211100118686',
 'SPPD21-2003',
 'LVM191100060034',
 'LVM230900100948',
 'NHP210100374',
 'CCSO22-3864',
 'SPPD23-4029',
 'LVM190900093348',
 'RPD22-22681',
 'CCSO22-6706',
 'HP19-18159',
 'NLPD2208040014491',
 'LVM220700017852',
 'LVM210700117672',
 'LVM211000028436',
 'LVM230600003333',
 'LVM200300087926',
 'LVM230700112251',
 'LVM210500107440',
 'LVM190100122781',
 'NLPD2105310009097',
 'LVM190500035233',
 'LVM210900033298',
 'LVM211200019452',
 'NHP210701744',
 'LVM210900030118',
 'NLPD2109300016841',
 'LVM200600106720',
 'SPPD22-7100',
 'LVM210800083226',
 'NLPD2005110007872',
 'LVM220200030854',
 'NLPD2310030019821',
 'LVM210500087076',
 'LVM200100017876',
 'HP21-17214',
 'RPD20-12077',
 'LVM210200103706',
 'LVM190500116647',
 'LVM190400138429',
 'LVM200100106642',
 'NLPD2105210008523',
 'RPD20-369',
 'RPD20-13630',
 'LVM230100031827',
 'LVM220900076431',
 'LVM220700089748',
 'LVM200400002702',
 'WASO20-4373',
 'LVM231000041015',
 'LVM221100018795',
 'RPD19-18153',
 'LVM200300128108',
 'LVM220900080202',
 'LVM210900016948',
 'RPD20-14529',
 'LVM191100109606',
 'LVM190900011455',
 ...}

In [33]:
sheet_crashes_bicyclist = sheet_crashes_no_dup.filter(pl.col('CrashNum').is_in(crash_nums_bicyclist))[:, columns_extract_crashes]
sheet_crashes_bicyclist

shape: (2_313, 14)
┌────────────┬────────────┬────────────┬───────────┬───┬────────┬───────────┬───────────┬──────────┐
│ CrashNum   ┆ Street1    ┆ Street1Oth ┆ Street1Lo ┆ … ┆ County ┆ CountyLoc ┆ X         ┆ Y        │
│ ---        ┆ ---        ┆ er         ┆ cated     ┆   ┆ ---    ┆ ated      ┆ ---       ┆ ---      │
│ str        ┆ str        ┆ ---        ┆ ---       ┆   ┆ str    ┆ ---       ┆ f64       ┆ f64      │
│            ┆            ┆ str        ┆ str       ┆   ┆        ┆ str       ┆           ┆          │
╞════════════╪════════════╪════════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪══════════╡
│ LVM2103000 ┆ ARVILLE ST ┆ null       ┆ ARVILLE   ┆ … ┆ CLARK  ┆ CLARK     ┆ 662005.19 ┆ 4.0007e6 │
│ 01603      ┆            ┆            ┆ ST        ┆   ┆        ┆           ┆ 02        ┆          │
│ NLPD230614 ┆ BENNETT ST ┆ null       ┆ BENNETT   ┆ … ┆ CLARK  ┆ CLARK     ┆ 666778.20 ┆ 4.0075e6 │
│ 0012098    ┆            ┆            ┆ ST        ┆   ┆        ┆           ┆ 52        ┆          │
│ NLPD210103 ┆ W CHEYENNE ┆ null       ┆ W         ┆ … ┆ CLARK  ┆ CLARK     ┆ 661491.98 ┆ 4.0096e6 │
│ 0000128    ┆ AVE        ┆            ┆ CHEYENNE  ┆   ┆        ┆           ┆ 8         ┆          │
│            ┆            ┆            ┆ AVE       ┆   ┆        ┆           ┆           ┆          │
│ SPPD19-692 ┆ E PRATER   ┆ null       ┆ E PRATER  ┆ … ┆ null   ┆ null      ┆ 266410.53 ┆ 4.3804e6 │
│ 5          ┆ WY         ┆            ┆ WY        ┆   ┆        ┆           ┆ 07        ┆          │
│ NHP2102007 ┆ OTHER      ┆ IR80/ E.   ┆ OTHER     ┆ … ┆ WASHOE ┆ WASHOE    ┆ 253948.90 ┆ 4.3788e6 │
│ 59         ┆            ┆ MCCARRRAN  ┆           ┆   ┆        ┆           ┆ 66        ┆          │
│            ┆            ┆ BLVD OFF   ┆           ┆   ┆        ┆           ┆           ┆          │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …        │
│ HP23-05355 ┆ N GREEN    ┆ null       ┆ WARM      ┆ … ┆ CLARK  ┆ CLARK     ┆ 672559.88 ┆ 3.9919e6 │
│            ┆ VALLEY     ┆            ┆ SPRINGS   ┆   ┆        ┆           ┆ 04        ┆          │
│            ┆ PKWY       ┆            ┆ RD        ┆   ┆        ┆           ┆           ┆          │
│ RPD21-1384 ┆ W MOANA LN ┆ null       ┆ W MOANA   ┆ … ┆ WASHOE ┆ WASHOE    ┆ 260074.87 ┆ 4.3752e6 │
│ 1          ┆            ┆            ┆ LN        ┆   ┆        ┆           ┆ 1         ┆          │
│ LVM2001000 ┆ S RAINBOW  ┆ null       ┆ S RAINBOW ┆ … ┆ CLARK  ┆ CLARK     ┆ 658160.07 ┆ 3.9963e6 │
│ 12625      ┆ BLVD       ┆            ┆ BLVD      ┆   ┆        ┆           ┆ 77        ┆          │
│ LVM2105001 ┆ E HARMON   ┆ null       ┆ E HARMON  ┆ … ┆ CLARK  ┆ CLARK     ┆ 664278.39 ┆ 3.9976e6 │
│ 11489      ┆ AVE        ┆            ┆ AVE       ┆   ┆        ┆           ┆ 72        ┆          │
│ LVM2208000 ┆ VEGAS DR   ┆ null       ┆ VEGAS DR  ┆ … ┆ CLARK  ┆ CLARK     ┆ 656452.49 ┆ 4.0063e6 │
│ 92738      ┆            ┆            ┆           ┆   ┆        ┆           ┆ 03        ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴────────┴───────────┴───────────┴──────────┘

## Write Data to file

In [34]:
path_out_pedestrian = Path('./crashes_pedestrian.csv')
path_out_bicyclist  = Path('./crashes_bicyclist.csv')

sheet_crashes_pedestrian.write_csv(path_out_pedestrian)
sheet_crashes_bicyclist.write_csv(path_out_bicyclist)

print("Wrote data.")

Wrote data.