In [16]:
# Imports
import polars as pl
import numpy as np
from IPython.display import display

In [3]:
# Read data from files (Will take long!)

excel_file_name = '5 YR 2019-2023 STATEWIDE CRASH DATA.xlsx'

print('Reading Excel files...')
data_crashes  = pl.read_excel(excel_file_name, sheet_name='2019-2023 STATEWIDE', read_options={'schema_sample_rows': None})
print('Read crashes sheet')
data_persons  = pl.read_excel(excel_file_name, sheet_name='PERSONS INVOLVED', read_options={'schema_sample_rows': None})
print('Read persons sheet')

Reading Excel files...

Could not determine dtype for column 37, falling back to string
Could not determine dtype for column 40, falling back to string
Could not determine dtype for column 42, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 46, falling back to string
Could not determine dtype for column 52, falling back to string
Could not determine dtype for column 53, falling back to string
Could not determine dtype for column 67, falling back to string
Could not determine dtype for column 68, falling back to string
Could not determine dtype for column 71, falling back to string

Read crashes sheet

Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 22, falling back to string
Could not determine dtype for column 24, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 42, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 49, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 55, falling back to string
Could not determine dtype for column 56, falling back to string
Could not determine dtype for column 57, falling back to string
Could not determine dtype for column 58, falling back to string
Could not determine dtype for column 59, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 61, falling back to string
Could not determine dtype for column 62, falling back to string
Could not determine dtype for column 63, falling back to string
Could not determine dtype for column 64, falling back to string
Could not determine dtype for column 65, falling back to string
Could not determine dtype for column 66, falling back to string
Could not determine dtype for column 67, falling back to string
Could not determine dtype for column 68, falling back to string
Could not determine dtype for column 69, falling back to string
Could not determine dtype for column 70, falling back to string
Could not determine dtype for column 71, falling back to string
Could not determine dtype for column 72, falling back to string
Could not determine dtype for column 73, falling back to string
Could not determine dtype for column 74, falling back to string
Could not determine dtype for column 75, falling back to string
Could not determine dtype for column 76, falling back to string
Could not determine dtype for column 77, falling back to string
Could not determine dtype for column 78, falling back to string
Could not determine dtype for column 79, falling back to string
Could not determine dtype for column 80, falling back to string
Could not determine dtype for column 81, falling back to string
Could not determine dtype for column 82, falling back to string
Could not determine dtype for column 83, falling back to string

Read persons sheet

In [5]:
data_crashes.head()

shape: (5, 74)
┌───────────────┬───────────────┬──────────────┬───────────────┬───┬───────────┬──────────────┬─────────────┬──────────┐
│ CrashNum      ┆ Street1       ┆ Street1Other ┆ Street1Locate ┆ … ┆ Measure   ┆ SecondaryCol ┆ X           ┆ Y        │
│ ---           ┆ ---           ┆ ---          ┆ d             ┆   ┆ ---       ┆ lision       ┆ ---         ┆ ---      │
│ str           ┆ str           ┆ str          ┆ ---           ┆   ┆ f64       ┆ ---          ┆ f64         ┆ f64      │
│               ┆               ┆              ┆ str           ┆   ┆           ┆ str          ┆             ┆          │
╞═══════════════╪═══════════════╪══════════════╪═══════════════╪═══╪═══════════╪══════════════╪═════════════╪══════════╡
│ DCSO19SO00071 ┆ TRAMWAY DR    ┆ null         ┆ TRAMWAY DR    ┆ … ┆ 0.1539596 ┆ null         ┆ 249866.4479 ┆ 4.3165e6 │
│ LVM1901000001 ┆ S 13TH ST     ┆ null         ┆ S 13TH ST     ┆ … ┆ 0.5510151 ┆ null         ┆ 667729.2167 ┆ 4.0033e6 │
│ 40            ┆               ┆              ┆               ┆   ┆           ┆              ┆             ┆          │
│ LVM1901000002 ┆ E HARMON AVE  ┆ null         ┆ E HARMON AVE  ┆ … ┆ 6.8884321 ┆ null         ┆ 675390.3576 ┆ 3.9979e6 │
│ 22            ┆               ┆              ┆               ┆   ┆           ┆              ┆             ┆          │
│ LVM1901000003 ┆ S RAINBOW     ┆ null         ┆ S RAINBOW     ┆ … ┆ 3.0583704 ┆ null         ┆ 658079.008  ┆ 4.0014e6 │
│ 91            ┆ BLVD          ┆              ┆ BLVD          ┆   ┆           ┆              ┆             ┆          │
│ LVM1901000006 ┆ PLANET        ┆ null         ┆ PLANET        ┆ … ┆ null      ┆ null         ┆ null        ┆ null     │
│ 83            ┆ HOLLYWOOD WAY ┆              ┆ HOLLYWOOD WAY ┆   ┆           ┆              ┆             ┆          │
└───────────────┴───────────────┴──────────────┴───────────────┴───┴───────────┴──────────────┴─────────────┴──────────┘

In [6]:
data_crashes.describe()

shape: (9, 75)
┌────────────┬──────────────┬──────────┬──────────────┬───┬────────────┬───────────────┬───────────────┬───────────────┐
│ statistic  ┆ CrashNum     ┆ Street1  ┆ Street1Other ┆ … ┆ Measure    ┆ SecondaryColl ┆ X             ┆ Y             │
│ ---        ┆ ---          ┆ ---      ┆ ---          ┆   ┆ ---        ┆ ision         ┆ ---           ┆ ---           │
│ str        ┆ str          ┆ str      ┆ str          ┆   ┆ f64        ┆ ---           ┆ f64           ┆ f64           │
│            ┆              ┆          ┆              ┆   ┆            ┆ str           ┆               ┆               │
╞════════════╪══════════════╪══════════╪══════════════╪═══╪════════════╪═══════════════╪═══════════════╪═══════════════╡
│ count      ┆ 251794       ┆ 251720   ┆ 64082        ┆ … ┆ 227372.0   ┆ 21847         ┆ 228231.0      ┆ 228231.0      │
│ null_count ┆ 0            ┆ 74       ┆ 187712       ┆ … ┆ 24422.0    ┆ 229947        ┆ 23563.0       ┆ 23563.0       │
│ mean       ┆ null         ┆ null     ┆ null         ┆ … ┆ 8.716773   ┆ null          ┆ 582051.106356 ┆ 4.0925e6      │
│ std        ┆ null         ┆ null     ┆ null         ┆ … ┆ 16.374273  ┆ null          ┆ 160624.16148  ┆ 166164.849679 │
│ min        ┆ 2110-089164  ┆ 10TH     ┆  CD          ┆ … ┆ 0.0        ┆ NO            ┆ 240563.0623   ┆ 3.8774e6      │
│ 25%        ┆ null         ┆ null     ┆ null         ┆ … ┆ 0.5188157  ┆ null          ┆ 649890.7486   ┆ 3.9974e6      │
│ 50%        ┆ null         ┆ null     ┆ null         ┆ … ┆ 2.7083614  ┆ null          ┆ 663724.6477   ┆ 4.0044e6      │
│ 75%        ┆ null         ┆ null     ┆ null         ┆ … ┆ 8.416142   ┆ null          ┆ 669172.398    ┆ 4.0215e6      │
│ max        ┆ YPD23YE-0010 ┆ ZUBIA ST ┆ YORK WAY EB  ┆ … ┆ 172.355573 ┆ YES           ┆ 763110.6127   ┆ 4.6513e6      │
└────────────┴──────────────┴──────────┴──────────────┴───┴────────────┴───────────────┴───────────────┴───────────────┘

In [7]:
data_persons.describe()

shape: (9, 85)
┌────────────┬──────────────┬─────────────┬─────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ statistic  ┆ CrashNum     ┆ pplNo       ┆ vcNoRelated ┆ … ┆ VehicleSeq1H ┆ NMVehActions ┆ NMVehActions ┆ NonMotorDam │
│ ---        ┆ ---          ┆ ---         ┆ ---         ┆   ┆ arm          ┆ ---          ┆ Other        ┆ ageArea     │
│ str        ┆ str          ┆ f64         ┆ f64         ┆   ┆ ---          ┆ str          ┆ ---          ┆ ---         │
│            ┆              ┆             ┆             ┆   ┆ str          ┆              ┆ str          ┆ str         │
╞════════════╪══════════════╪═════════════╪═════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ count      ┆ 705481       ┆ 705481.0    ┆ 705481.0    ┆ … ┆ 14884        ┆ 2781         ┆ 76           ┆ 2533        │
│ null_count ┆ 0            ┆ 0.0         ┆ 0.0         ┆ … ┆ 690597       ┆ 702700       ┆ 705405       ┆ 702948      │
│ mean       ┆ null         ┆ 5.5481e7    ┆ 5.0670e7    ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ std        ┆ null         ┆ 1.7986e7    ┆ 2.1251e7    ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ min        ┆ 2110-089164  ┆ 3.4115667e7 ┆ 0.0         ┆ … ┆ 0            ┆ ENTERING     ┆ BACKING      ┆ BOTTOM|     │
│            ┆              ┆             ┆             ┆   ┆              ┆ LANE         ┆              ┆             │
│ 25%        ┆ null         ┆ 3.6029819e7 ┆ 3.4341836e7 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 50%        ┆ null         ┆ 6.3637465e7 ┆ 4.3345487e7 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 75%        ┆ null         ┆ 7.2486622e7 ┆ 6.9958834e7 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ max        ┆ YPD23YE-0010 ┆ 9.2517998e7 ┆ 8.8506042e7 ┆ … ┆ 5            ┆ Unknown      ┆ WRONG WAY IN ┆ Unknown     │
│            ┆              ┆             ┆             ┆   ┆              ┆              ┆ BIKE LANE    ┆             │
└────────────┴──────────────┴─────────────┴─────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [8]:
data_persons.head()

shape: (5, 84)
┌──────────────┬──────────┬─────────────┬────────────┬───┬───────────────┬──────────────┬───────────────┬──────────────┐
│ CrashNum     ┆ pplNo    ┆ vcNoRelated ┆ PersonType ┆ … ┆ VehicleSeq1Ha ┆ NMVehActions ┆ NMVehActionsO ┆ NonMotorDama │
│ ---          ┆ ---      ┆ ---         ┆ ---        ┆   ┆ rm            ┆ ---          ┆ ther          ┆ geArea       │
│ str          ┆ i64      ┆ i64         ┆ str        ┆   ┆ ---           ┆ str          ┆ ---           ┆ ---          │
│              ┆          ┆             ┆            ┆   ┆ str           ┆              ┆ str           ┆ str          │
╞══════════════╪══════════╪═════════════╪════════════╪═══╪═══════════════╪══════════════╪═══════════════╪══════════════╡
│ BCPD23BC0278 ┆ 75414953 ┆ 73288159    ┆ Driver     ┆ … ┆ null          ┆ null         ┆ null          ┆ null         │
│ CCSO23-1321  ┆ 75317726 ┆ 73199548    ┆ Driver     ┆ … ┆ null          ┆ null         ┆ null          ┆ null         │
│ CCSO23-1321  ┆ 75317727 ┆ 73199548    ┆ Passenger  ┆ … ┆ null          ┆ null         ┆ null          ┆ null         │
│ CCSO23-1321  ┆ 75317728 ┆ 73199549    ┆ Driver     ┆ … ┆ null          ┆ null         ┆ null          ┆ null         │
│ CCSO23-1321  ┆ 75318129 ┆ 0           ┆ Witness    ┆ … ┆ null          ┆ null         ┆ null          ┆ null         │
└──────────────┴──────────┴─────────────┴────────────┴───┴───────────────┴──────────────┴───────────────┴──────────────┘

In [9]:
print('Crashes Sheet Columns:', *sorted(data_crashes.columns, key=lambda s: s.lower()), sep='\n * ')

Crashes Sheet Columns:
 * AgencyName
 * AlcoholInvolved
 * AreaOfInitialImpact
 * ArrivedDate
 * ArrivedTime
 * Beat
 * City
 * County
 * CountyLocated
 * CrashDate
 * CrashNum
 * CrashSeverity
 * CrashTime
 * CrashType
 * DirFromLandmark
 * DirFromLandmarkLocated
 * DistFromLandmark
 * DistFromLandmarkLocated
 * DistLandmarkApprox
 * FirstHarmfulEventDesc
 * HitandRun
 * IncidentClearanceTime
 * Intersection
 * LandmarkUnit
 * LightCondition
 * LightConditionOther
 * Location
 * LocationFirstEvent
 * LocationFirstEventOther
 * LocationFirstEventTrav
 * LocationFirstEventTurn
 * Measure
 * MilePost
 * MotorcycleInvolved
 * NotifiedDate
 * NotifiedTime
 * NumFatalities
 * NumInjured
 * NumNonMotorists
 * NumOccupants
 * NumRestrained
 * NumVehicles
 * OfficeReport
 * OutsideTown
 * PedestrianInvolved
 * PrivateProperty
 * PropertyDamage
 * PropertyDamageDesc
 * ReportComplete
 * ReportDate
 * RoadEnvironFactorsOtherEnv
 * RoadEnvironFactorsOtherHwy
 * RoadEnvironmentalFactors
 * RoadIntersectType
 * RoadIntersectTypeOther
 * RoadPaddleMarkers
 * RoadSurface
 * RoadSurfaceOther
 * RoadwayClearanceTime
 * RouteID
 * SchoolZone
 * SecondaryCollision
 * Street1
 * Street1Located
 * Street1Other
 * Street2
 * Street2Located
 * Street2Other
 * TrafficControlOther
 * VehCrashType
 * Weather
 * WeatherOther
 * X
 * Y

In [10]:
data_crashes_nm = data_crashes.filter(pl.col('NumNonMotorists') >= 1)
data_crashes_nm.shape

(8143, 74)

In [11]:
data_crashes_nm[:, 'PedestrianInvolved'].value_counts()

shape: (3, 2)
┌────────────────────┬───────┐
│ PedestrianInvolved ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ YES                ┆ 4811  │
│ null               ┆ 1     │
│ NO                 ┆ 3331  │
└────────────────────┴───────┘

In [12]:
data_crashes_pi = data_crashes.filter(pl.col('PedestrianInvolved') == 'YES')
data_crashes_pi.shape

(4811, 74)

In [13]:
data_crashes_pi[:, 'NumNonMotorists'].value_counts()

shape: (6, 2)
┌─────────────────┬───────┐
│ NumNonMotorists ┆ count │
│ ---             ┆ ---   │
│ i64             ┆ u32   │
╞═════════════════╪═══════╡
│ 3               ┆ 32    │
│ 5               ┆ 2     │
│ 2               ┆ 239   │
│ 6               ┆ 3     │
│ 4               ┆ 5     │
│ 1               ┆ 4530  │
└─────────────────┴───────┘

In [14]:
print('Persons Sheet Columns:', *sorted(data_persons.columns, key=lambda s: s.lower()), sep='\n * ')

Persons Sheet Columns:
 * Age
 * AirBag
 * AirbagSwitch
 * AlcDrugInvolved
 * CrashNum
 * DeathDate
 * DeathTime
 * DLClass
 * DLCommercial
 * DLStatus
 * Driver
 * DrugResults
 * DrugResults2
 * DrugResults3
 * DrugSpecimen1
 * DrugSpecimen2
 * Ejected
 * FieldSobrietyTest
 * Helmet
 * HitRunPerson
 * InjuryCode
 * InjuryLocation1
 * InjuryLocation2
 * InjuryLocation3
 * NMActions
 * NMActionsOther
 * NMBikeLane
 * NMBikeLaneOther
 * NMCondition
 * NMConditionOther
 * NMDirOfTravel
 * NMFactor
 * NMFactorOther
 * NMLocPrior2Imp
 * NMLocPrior2ImpOther
 * NMNumVehStrike1
 * NMNumVehStrike2
 * NMNumVehStrike3
 * NMPedDamage
 * NMSafetyEquip
 * NMSafetyEquipOther
 * NMSpeedHigh
 * NMSpeedLimit
 * NMSpeedLow
 * NMStreetName
 * NMTypeOther
 * NMVehActions
 * NMVehActionsOther
 * NonMotorDamageArea
 * NonMotorist
 * NonMotoristContact
 * NonMotoristFault
 * NumberOfCitations
 * PersonFactInatt
 * PersonFactors
 * PersonType
 * pplNo
 * Race
 * RestraintUsed
 * SeatPosition
 * Sex
 * SuspectedImpairment
 * Trapped
 * UrineBloodRes
 * vcNoRelated
 * VehicleDamage1stCon
 * VehicleDamageRating1
 * VehicleMake
 * VehicleModel
 * VehicleSeq1CFO
 * VehicleSeq1Code
 * VehicleSeq1Harm
 * VehicleSeq2CFO
 * VehicleSeq2Code
 * VehicleSeq3CFO
 * VehicleSeq3Code
 * VehicleSeq4CFO
 * VehicleSeq4Code
 * VehicleSeq5CFO
 * VehicleSeq5Code
 * VehicleSerialNo
 * VehicleType
 * VehOwner
 * VehUnit

In [17]:
data_persons[:, 'PersonType'].value_counts(sort=True)

shape: (20, 2)
┌────────────────┬────────┐
│ PersonType     ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ Driver         ┆ 479004 │
│ Passenger      ┆ 173411 │
│ Witness        ┆ 44205  │
│ Pedestrian     ┆ 5128   │
│ Pedal Cyclist  ┆ 2331   │
│ …              ┆ …      │
│ Police         ┆ 37     │
│ null           ┆ 20     │
│ Other Cyclist  ┆ 6      │
│ Tow Operator   ┆ 1      │
│ Transportation ┆ 1      │
└────────────────┴────────┘

In [70]:
data_persons_ped = data_persons.filter(pl.col('PersonType') == 'Pedestrian')
data_persons_ped

shape: (5_128, 84)
┌───────────────┬──────────┬─────────────┬────────────┬───┬───────────────┬──────────────┬──────────────┬──────────────┐
│ CrashNum      ┆ pplNo    ┆ vcNoRelated ┆ PersonType ┆ … ┆ VehicleSeq1Ha ┆ NMVehActions ┆ NMVehActions ┆ NonMotorDama │
│ ---           ┆ ---      ┆ ---         ┆ ---        ┆   ┆ rm            ┆ ---          ┆ Other        ┆ geArea       │
│ str           ┆ i64      ┆ i64         ┆ str        ┆   ┆ ---           ┆ str          ┆ ---          ┆ ---          │
│               ┆          ┆             ┆            ┆   ┆ str           ┆              ┆ str          ┆ str          │
╞═══════════════╪══════════╪═════════════╪════════════╪═══╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ LVM2303000439 ┆ 75532677 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ 00            ┆          ┆             ┆            ┆   ┆               ┆              ┆              ┆              │
│ RPD22-106058  ┆ 70255658 ┆ 0           ┆ Pedestrian ┆ … ┆ null          ┆ null         ┆ null         ┆ null         │
│ RPD22-12123   ┆ 70248504 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ LVM2207000061 ┆ 70172151 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ 86            ┆          ┆             ┆            ┆   ┆               ┆              ┆              ┆              │
│ RPD22-21215   ┆ 73000579 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ …             ┆ …        ┆ …           ┆ …          ┆ … ┆ …             ┆ …            ┆ …            ┆ …            │
│ HP23-23852    ┆ 82007077 ┆ 0           ┆ Pedestrian ┆ … ┆ null          ┆ null         ┆ null         ┆ null         │
│ RPD23-23068   ┆ 82302178 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ NHP231201156  ┆ 82377466 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ RPD23-23349   ┆ 82412785 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
│ HP23-24173    ┆ 82098513 ┆ 0           ┆ Pedestrian ┆ … ┆ 1             ┆ null         ┆ null         ┆ null         │
└───────────────┴──────────┴─────────────┴────────────┴───┴───────────────┴──────────────┴──────────────┴──────────────┘

In [71]:
data_persons_ped[:, 'InjuryCode'].value_counts()

shape: (8, 2)
┌────────────┬───────┐
│ InjuryCode ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ null       ┆ 92    │
│ A          ┆ 786   │
│ C          ┆ 1617  │
│ N          ┆ 48    │
│ K          ┆ 385   │
│ B          ┆ 1814  │
│ U          ┆ 93    │
│ O          ┆ 293   │
└────────────┴───────┘

In [73]:
set(data_crashes.columns) & set(data_persons.columns)

{'CrashNum'}

In [84]:
data_crashes[:, 'CrashNum'].is_unique().value_counts()

shape: (2, 2)
┌──────────┬────────┐
│ CrashNum ┆ count  │
│ ---      ┆ ---    │
│ bool     ┆ u32    │
╞══════════╪════════╡
│ false    ┆ 42     │
│ true     ┆ 251752 │
└──────────┴────────┘

In [88]:
# Duplicate values??
data_crashes_dup = data_crashes.filter(pl.col('CrashNum').is_duplicated()).sort('CrashNum')

In [ ]:
data_crashes_dup.filter(pl.col('NonMotoristsNum'))

In [77]:
data_joined = data_crashes.join(data_persons, how='inner', on='CrashNum')
data_joined

shape: (705_576, 157)
┌──────────────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ CrashNum     ┆ Street1      ┆ Street1Other ┆ Street1Loca ┆ … ┆ VehicleSeq1 ┆ NMVehAction ┆ NMVehAction ┆ NonMotorDam │
│ ---          ┆ ---          ┆ ---          ┆ ted         ┆   ┆ Harm        ┆ s           ┆ sOther      ┆ ageArea     │
│ str          ┆ str          ┆ str          ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆              ┆              ┆ str         ┆   ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ BCPD23BC0278 ┆ CASCATA DR   ┆ null         ┆ CASCATA DR  ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ CCSO23-1321  ┆ S CARSON ST  ┆ null         ┆ US395S      ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ CCSO23-1321  ┆ S CARSON ST  ┆ null         ┆ US395S      ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ CCSO23-1321  ┆ S CARSON ST  ┆ null         ┆ US395S      ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ CCSO23-1321  ┆ S CARSON ST  ┆ null         ┆ US395S      ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ …            ┆ …            ┆ …            ┆ …           ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ LVM230900088 ┆ E FLAMINGO   ┆ null         ┆ SR592       ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 010          ┆ RD           ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ LVM230900088 ┆ E FLAMINGO   ┆ null         ┆ SR592       ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 010          ┆ RD           ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ LVM230900088 ┆ W OAKEY BLVD ┆ null         ┆ W OAKEY     ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 040          ┆              ┆              ┆ BLVD        ┆   ┆             ┆             ┆             ┆             │
│ LVM230900088 ┆ STEPHANIE ST ┆ null         ┆ STEPHANIE   ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 071          ┆              ┆              ┆ ST          ┆   ┆             ┆             ┆             ┆             │
│ LVM230900088 ┆ STEPHANIE ST ┆ null         ┆ STEPHANIE   ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 071          ┆              ┆              ┆ ST          ┆   ┆             ┆             ┆             ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [13]:
data_joined = data_crashes.join(data_persons, how='inner', on='CrashNum')
crash_nums_joined = set(data_joined[:, 'CrashNum'])
crash_nums_crashes = set(data_crashes[:, 'CrashNum'])

print(f'{len(crash_nums_joined) = }')
print(f'{len(crash_nums_crashes) = }')
print(f'{data_joined[:, 'CrashNum'].value_counts()[:, 'count'].value_counts(name='freq').sort(by='count') = }')

len(crash_nums_joined) = 251506
len(crash_nums_crashes) = 251773
data_joined[:, 'CrashNum'].value_counts()[:, 'count'].value_counts(name='freq').sort(by='count') = shape: (38, 2)
┌───────┬────────┐
│ count ┆ freq   │
│ ---   ┆ ---    │
│ u32   ┆ u32    │
╞═══════╪════════╡
│ 1     ┆ 30674  │
│ 2     ┆ 103476 │
│ 3     ┆ 58904  │
│ 4     ┆ 29398  │
│ 5     ┆ 15028  │
│ …     ┆ …      │
│ 43    ┆ 1      │
│ 46    ┆ 1      │
│ 52    ┆ 1      │
│ 57    ┆ 1      │
│ 76    ┆ 1      │
└───────┴────────┘